<?php
#**************************************************************************#
#   MolyX2
#   ------------------------------------------------------
#   copyright (c) 2004-2006 HOGE Software.
#   official forum : http://molyx.com
#   license : MolyX License, http://molyx.com/license
#   MolyX2 is free software. You can redistribute this file and/or modify
#   it under the terms of MolyX License. If you do not accept the Terms
#   and Conditions stated in MolyX License, please do not redistribute
#   this file.Please visit http://molyx.com/license periodically to review
#   the Terms and Conditions, or contact HOGE Software.
#**************************************************************************#
$a_lang = array(
	'install' => array()
);

$a_lang['install']['versiontoolow'] = '由於 PHP 版本太低( < 4.0.6 )，MolyX BOARD 無法正常安裝。<br>請聯繫伺服器管理員升級PHP。';
$a_lang['install']['script'] = '安裝腳本';
$a_lang['install']['studios'] = '魔力論壇魔力體驗 - MolyX Magic Experience';
$a_lang['install']['customsupport'] = '版權所有: 南京厚建軟件有限責任公司';
$a_lang['install']['next'] = '下一步';
$a_lang['install']['back'] = '返回';
$a_lang['install']['error'] = '錯誤';
$a_lang['install']['login'] = '登入';
$a_lang['install']['adminpwtooshort'] = '管理員密碼設定太短了，請將密碼設定在 5 個字元以上!';
$a_lang['install']['passwordnowmatch'] = '兩次輸入的密碼不一致，請返回重試。';
$a_lang['install']['chmoderror'] = '無法寫入配置檔案！<br />請將 ../includes/config.php 檔案屬性設定為 CHMOD 0755, CHMOD 0775 或 CHMOD 0777 (如果無法確認的話，設定為 0777) 並刷新本頁面。. 或者你可以在上一步下載一份程式生成的配置檔案，放置到此檔案夾內。點擊後退按鈕選擇你要操作的其他方式。';
$a_lang['install']['mysqlerror'] = '無法創建資料庫 "%s": <b>%s</b>';
$a_lang['install']['connecterror'] = '無法連接資料庫，請確認填寫了正確的用戶名和密碼。<br />MySQL 返回結果: <b>%s</b>';
$a_lang['install']['queryerror'] = '執行查詢錯誤: <i>%s</i><br /><br />MySQL 返回結果: <b>%s</b>';
$a_lang['install']['installation'] = '安裝腳本';
$a_lang['install']['licagreement'] = '使用協定聲明';
$a_lang['install']['licread'] = '我已閱讀並完全同意以上聲明';
$a_lang['install']['licaccept'] = '必須同意我們的協議聲明才能繼續進行下一步的安裝。';
$a_lang['install']['canwrite'] = '可寫';
$a_lang['install']['cannotwrite'] = '不可寫';
$a_lang['install']['dircontinue'] = '系統檔案夾檢查無誤，您可以進行下一步的安裝。';
$a_lang['install']['dirnotcontinue'] = '系統中的一個或多個檔案夾不可寫，您需要將上面出現的紅色檔案夾屬性設定為0777模式，安裝無法繼續。請檢查檔案夾屬性後重新刷新此頁面。';
$a_lang['install']['directory'] = '檔案夾';
$a_lang['install']['file'] = '檔案';
$a_lang['install']['mysqldata'] = '資料庫資訊';
$a_lang['install']['entermysqldata'] = '請在下表填寫你的資料庫資訊。';
$a_lang['install']['dbtype'] = '資料庫類型';
$a_lang['install']['dbhost'] = '資料庫主機名/IP位址';
$a_lang['install']['dbuser'] = '資料庫用戶名';
$a_lang['install']['dbpass'] = '資料庫密碼';
$a_lang['install']['dbcharset'] = '請設定資料庫連接方式';
$a_lang['install']['set_dbcharset'] = '由於您的MySQL資料庫版本大於 4.1 且您的默認資料庫字元集不為UTF-8，因此請在下面設定您的資料庫字元集連接方式。注意！不正確的設定可能會無法成功安裝程式！';
$a_lang['install']['current_char'] = '當前字元集類型';
$a_lang['install']['recommend_char'] = '推薦填寫';
$a_lang['install']['selectdb'] = '請選擇資料庫';
$a_lang['install']['choosedb'] = '請在下面功能表中選擇用於安裝本系統的資料庫，或者在下面直接輸入資料庫名稱。如果資料庫不存在的話，系統將嘗試創建新庫。';
$a_lang['install']['existingdb'] = '現有庫';
$a_lang['install']['usefield'] = '使用填寫的資料庫';
$a_lang['install']['orname'] = '<b>或者</b>填寫資料庫名稱:';
$a_lang['install']['chooseprefix'] = '請選擇 MySQL 資料表首碼';
$a_lang['install']['tablelist'] = '資料庫 <b>"%s"</b> 當前包含以下資料表:';
$a_lang['install']['enterprefix'] = '<p>請輸入用於每個資料表開始部分的首碼。如果使用首碼的話，你就可以在同一資料庫內安裝多個相同的 MolyX BOARD。</p> 資料表首碼:';
$a_lang['install']['dontchange'] = '如果不清楚的話，不要更改此設定';
$a_lang['install']['deleteexisting'] = '覆蓋(刪除)已有資料表';
$a_lang['install']['importstyles'] = '下一步將開始導入論壇風格設定，請確認在安裝檔案夾記憶體在 MolyX-style.xml 檔案';
$a_lang['install']['styleexists'] = '風格 MolyX-style.xml 檔案存在，可以執行導入。';
$a_lang['install']['stylenotexists'] = '風格 MolyX-style.xml 檔案不存在，無法完成導入';
$a_lang['install']['createadmin'] = '創建管理員帳號';
$a_lang['install']['sitesettings'] = '論壇參數設定';
$a_lang['install']['hometitle'] = '<b>網站名稱</b>';
$a_lang['install']['homeurl'] = '<b>網站地址</b>';
$a_lang['install']['bbtitle'] = '<b>論壇名稱</b>';
$a_lang['install']['bburl'] = '<b>論壇地址</b>';
$a_lang['install']['emailreceived'] = '<b>用於接收信件的郵箱位址</b>';
$a_lang['install']['emailsend'] = '<b>用於傳送信件的郵箱地址</b>';
$a_lang['install']['cookiedomain'] = '<b>Cookie 作用域</b><br />即你想使本論壇的cookie起作用的範圍。如果你想將此效果作用於你的網站“yourhost.com”，而不僅僅是“forums.yourhost.com”，那請在這裏輸入“.yourhost.com”(注意有兩個點！)。本項可以留空。';
$a_lang['install']['cookieprefix'] = '<b>Cookie 首碼</b><br />可以此設定在單一主機上安裝多個論壇。';
$a_lang['install']['cookiepath'] = '<b>保存 Cookies 的路徑</b><br />保存cookies的路徑。如果在同一個功能變數名稱裏運行不止一個論壇，最好各個論壇設定不同的路徑。';
$a_lang['install']['cantexec'] = '升級程式無法正確執行。(版本號不匹配)';
$a_lang['install']['updatenotes'] = '請核對安裝檔案是否與當前論壇版本相匹配後再決定是否升級<br />不正確的升級版本檔案可能會造成系統損壞。';
$a_lang['install']['defaultstyle'] = '默認風格';
$a_lang['install']['xmlparseerror'] = 'XML解析錯誤';
$a_lang['install']['atlines'] = '於行號';
$a_lang['install']['styleerror'] = '無效的風格檔案。';
$a_lang['install']['username'] = '用戶名';
$a_lang['install']['email'] = '郵件';
$a_lang['install']['password'] = '密碼';
$a_lang['install']['twopassword'] = '確認密碼';
$a_lang['install']['completing'] = '安裝已成功完成！';
$a_lang['install']['completingtxt'] = '在完成安裝前，需要將資料庫配置檔案保存在伺服器內。創建這個配置檔案需要伺服器的 <b>../includes/</b> 檔案夾有寫入許可權。請再次確認此檔案夾許可權後繼續。如果不清楚如何操作的話，請將此檔案夾許可權設定為 0777 模式，Windows 系統不用考慮許可權設定。<br /><br /><b>注意:</b> 你也可以下載一份程式創建的 config.php 檔案並上傳到 <b>../includes/</b> 檔案夾內。請注意在你上傳了這個檔案後，安裝程式已經全部執行完成，本安裝程式將不可用。<br /><br /><a href="install.php?action=generate_config&amp;lang=zh-tw&amp;hostname=%s&amp;user=%s&amp;pass=%s&amp;db=%s&amp;prefix=%s&amp;usepconnect=%s&amp;superadmin=%s">下載配置檔案</a>';
$a_lang['install']['denied'] = '論壇已安裝';
$a_lang['install']['deniedtxt'] = '論壇已經安裝！如果你要升級論壇，請<a href="%s">點擊這裏</a><br /><br />如果你需要重新安裝論壇，請刪除 <b>../includes/config.php</b> 後再重新嘗試。';
$a_lang['install']['selectupdate'] = '請從下面的列表中選擇要更新的資訊。';
$a_lang['install']['updateinfo'] = '更新資訊';
$a_lang['install']['enteradminname'] = '請輸入正確的管理員帳號！！';
$a_lang['install']['reqver'] = '所需版本';
$a_lang['install']['nowupdatetable'] = '正在更新資料表';
$a_lang['install']['newver'] = '更新後版本';
$a_lang['install']['author'] = '作者';
$a_lang['install']['date'] = '日期';
$a_lang['install']['executable'] = '執行？';
$a_lang['install']['notes'] = '注釋';
$a_lang['install']['yes'] = '是';
$a_lang['install']['no'] = '否';
$a_lang['install']['na'] = 'N/A';
$a_lang['install']['infotxt'] = '
                      <p>
                      在接下來的安裝過程中本腳本將幫助您將程式完整搭建在您的伺服器內。請您先確認以下安裝配置:                      </p>
                    <ul>
                      <li>MySQL 主機名稱/IP 位址</li>
                      <li>MySQL 用戶名和密碼</li>
                      <li>MySQL 資料庫名稱 (如果沒有創建新資料庫的許可權)</li>
					  <li>./CACHE 檔案夾及子檔案夾許可權為 0777 (UNIX系統)</li>
					  <li>./DATA 檔案夾及子檔案夾許可權為 0777 (UNIX系統)</li>
					  <li>./includes/config.php 檔案許可權為 0777 (UNIX系統)</li>
                    </ul>
					以上的配置資訊您可以在 includes/config.php 檔案內直接配置；更改檔案夾，檔案許可權請自行在FTP內更改。如果您無法確認以上的配置資訊，請與您的服務商聯繫，我們無法為您提供任何幫助。
					<br />
                    <br />
					如果在安裝的過程中出現了任何問題，請您訪問我們的<a href="http://www.molyx.com/" target="_blank">技術支援論壇</a>
					<br />
                    <br />
					點擊下一步，將開始進行安裝 MolyX Board。';
$a_lang['install']['finished'] = '
<b>安裝已成功完成！</b><br />
<br />
如果使用的是UNIX 系統，請將 <b>../includes/</b> 檔案夾的訪問許可權設定為 0755.<br />
<br />
安裝已成功完成。你可以從下面的鏈結訪問論壇:<br />
<ul>
<li><a target="_blank" href="../">MolyX Board 主檔案夾</a></li>
<li><a target="_blank" href="../admin/index.php">MolyX Board 管理面板</a></li>
<li><a target="_blank" href="http://www.molyx.com/">MolyX Board 技術支援論壇</a></li>
</ul>';
$a_lang['install']['updatefinished'] = '
<b>升級已成功完成！</b><br />
<br />
<b>請在升級後重新建立緩存，並重新生成論壇全部範本，否則系統改動可能無法生效。<br /><br />為確保系統安全，請在升級後刪除 install 檔案夾！</b><br />
<br />
你可以從下面的鏈結訪問論壇:<br />
<ul>
<li><a target="_blank" href="%s">MolyX Board 首頁</a></li>
<li><a target="_blank" href="%s">MolyX Board 管理面板</a></li>
<li><a target="_blank" href="http://www.molyx.com/">MolyX Board 技術支援論壇</a></li>
</ul>';
$a_lang['install']['noupdates'] = '
<b>更新資訊</b><br />
<br />
目前無可用更新<br />
請訪問 <a href="http://www.molyx.com/">MolyX 主頁</a> 獲取更多更新腳本。'; 
$a_lang['mysql']['award']['bbsbulid'] = '論壇建設獎'; 
$a_lang['mysql']['award']['bbsbulidexplain'] = '你對社區建設作出了不可磨滅的貢獻，特發此獎。'; 
$a_lang['mysql']['award']['goodlove'] = '最佳情侶獎'; 
$a_lang['mysql']['award']['goodlovexplain'] = '不多說了，祝你們在以後的日子裏更加幸福！'; 
$a_lang['mysql']['award']['excellencemod'] = '優秀斑竹獎'; 
$a_lang['mysql']['award']['excellencemodepl'] = '在您的管理的版面裏會員熱情高漲，特發此獎，請繼續努力。'; 
$a_lang['mysql']['award']['bestproduce'] = '最佳創作獎'; 
$a_lang['mysql']['award']['bestproducepl'] = '你的創作有獨到的新意，讓大家受益非淺，特發此獎，請繼續努力喔。'; 
$a_lang['mysql']['award']['pourgenius'] = '灌水天才獎'; 
$a_lang['mysql']['award']['pourgeniusepl'] = '你灌水真是厲害呀，值得大家學習，特發此獎。'; 
$a_lang['mysql']['award']['pasteimgmaster'] = '貼圖大師獎'; 
$a_lang['mysql']['award']['pasteimgmasterepl'] = '您的貼圖真不錯，特發此獎，請繼續努力。'; 
$a_lang['mysql']['award']['bbsencourge'] = '論壇鼓勵獎'; 
$a_lang['mysql']['award']['bbsencourgepl'] = '由於你的努力，帶動了大家的熱情，特發此獎，希望你繼續成為大家學習的目標。'; 
$a_lang['mysql']['award']['bbskavass'] = '論壇衛士獎'; 
$a_lang['mysql']['award']['bbskavassepl'] = '由於你的關心，讓我們的論壇能在一片清靜的天空中發展，特發此獎。'; 
$a_lang['mysql']['award']['chatgenius'] = '聊天天才獎'; 
$a_lang['mysql']['award']['chatgeniusepl'] = '聊吧聊吧'; 
$a_lang['mysql']['award']['beautyuse'] = '美眉專用章'; 
$a_lang['mysql']['award']['beautyusepl'] = '各位帥哥請注意哈！'; 
$a_lang['mysql']['award']['handsomeuse'] = '帥哥專用章'; 
$a_lang['mysql']['award']['handsomeusepl'] = '各位美眉請注意喔！'; 
$a_lang['mysql']['award']['bestflack'] = '最佳宣傳獎'; 
$a_lang['mysql']['award']['bestflackepl'] = '由於你的帶動，使我們的論壇人氣更旺，特發此獎，加油喔。'; 
$a_lang['mysql']['award']['humormaster'] = '幽默大師獎'; 
$a_lang['mysql']['award']['humormasterepl'] = '你總能給人們帶來歡樂，特發此獎。'; 
$a_lang['mysql']['banfilter']['admin'] = '管理員'; 
$a_lang['mysql']['banfilter']['mod'] = '版主'; 
$a_lang['mysql']['bbcode']['tagforthread'] = '此標籤方便你快速定位一個主題的位置。'; 
$a_lang['mysql']['bbcode']['tagforpost'] = '此標籤方便你快速定位一個帖子的位置。'; 
$a_lang['mysql']['bbcode']['viewthread'] = '查看主題'; 
$a_lang['mysql']['bbcode']['viewpost'] = '查看帖子'; 
$a_lang['mysql']['bbcode']['tagforallmovie'] = '標籤允許貼各種格式的電影。'; 
$a_lang['mysql']['bbcode']['tagforallrmmovie'] = '標籤允許貼各種RM格式的電影。'; 
$a_lang['mysql']['bbcode']['clickdown'] = '點此下載'; 
$a_lang['mysql']['bbcode']['tagforallmusic'] = '標籤允許貼各種格式的音樂。'; 
$a_lang['mysql']['cron']['cleanout'] = '每小時資料清理'; 
$a_lang['mysql']['cron']['cleanoutdesc'] = '刪除無效的驗證資料，Sessions，搜尋資料'; 
$a_lang['mysql']['cron']['rebuildstats'] = '每日重建論壇統計'; 
$a_lang['mysql']['cron']['rebuildstatsdesc'] = '重建論壇統計'; 
$a_lang['mysql']['cron']['dailycleanout'] = '每日資料清理'; 
$a_lang['mysql']['cron']['dailycleanoutdesc'] = '清除無效的主題訂閱'; 
$a_lang['mysql']['cron']['birthdays'] = '每日生日會員'; 
$a_lang['mysql']['cron']['birthdaysdesc'] = '建立每天過生日會員緩存'; 
$a_lang['mysql']['cron']['announcements'] = '更新公告'; 
$a_lang['mysql']['cron']['announcementsdesc'] = '清除超過公告終止時間的公告'; 
$a_lang['mysql']['cron']['renameupload'] = '更改上傳檔案夾名稱'; 
$a_lang['mysql']['cron']['renameuploaddesc'] = '防止用戶盜鏈檔案地址，定時更改上傳檔案夾檔案夾名稱'; 
$a_lang['mysql']['cron']['promotion'] = '用戶晉級'; 
$a_lang['mysql']['cron']['promotiondesc'] = '每小時根據晉級策略更新用戶的所在用戶組'; 
$a_lang['mysql']['cron']['bankloancheck'] = '貸款清查及欠款強制收回'; 
$a_lang['mysql']['cron']['bankloancheckdesc'] = '清查當日貸款到期未還用戶，強制收回貸款，有必要的話變賣道具、積分進行償還，如仍不夠，個人破產，封禁用戶'; 
$a_lang['mysql']['cron']['bankpayinterest'] = '支付存款利息'; 
$a_lang['mysql']['cron']['bankpayinterestdesc'] = '按照日利率向所有帳戶狀態正常的存款用戶支付每日存款利息'; 
$a_lang['mysql']['cron']['award_promotion'] = '自動頒發勳章'; 
$a_lang['mysql']['cron']['award_promotiondesc'] = '通過本任務可以自動對符合條件的用戶授予勳章'; 
$a_lang['mysql']['cron']['rebuildglobalstick'] = '重建總置頂主題'; 
$a_lang['mysql']['cron']['rebuildglobalstickdesc'] = '重新建立總置頂主題的各種相關資訊'; 
$a_lang['mysql']['cron']['cleantoday'] = '更新每日發帖資訊'; 
$a_lang['mysql']['cron']['cleantodaydesc'] = '每天0點重置今日發帖資訊'; 
$a_lang['mysql']['cron']['refreshjs'] = '刷新JS生成代碼'; 
$a_lang['mysql']['cron']['refreshjsdesc'] = '在這裏刷新 JavaScript 調用設定的參數'; 
$a_lang['mysql']['faq']['faqtitle_1'] = "用戶維護";
$a_lang['mysql']['faq']['faqdesc_1'] = "這部分是關於如何維護你的個人資料、頭像以及流覽設定等等的資訊。";
$a_lang['mysql']['faq']['faqtitle_2'] = "論壇常規使用方法";
$a_lang['mysql']['faq']['faqtitle_3'] = "閱讀和發佈資訊";
$a_lang['mysql']['faq']['faqtitle_4'] = "我為什麼要註冊？";
$a_lang['mysql']['faq']['faqtext_4'] = "管理員可能要求你必須註冊為會員才可以使用論壇的全部功能。註冊是免費的，同時註冊後你可以獲得下列權利:<br /><br /><ul><br />	<li>發佈新主題</li><br /><li>回覆其他人的主題</li><br />	<li>編輯你的帖子</li><br />	<li>傳送短消息給其他會員</li><br />	<li>下載論壇附件</li><br /></ul><br /><br />如果要註冊的話，你需要指定一個用戶名、密碼以及一個有效的郵箱位址。請放心，你所輸入的郵箱位址在未經許可的情況下並不會給你傳送任何“垃圾郵件”，你可以選擇隱藏你的郵箱位址，那樣在任何時候其他人給你傳送郵件都不會顯示你的郵箱位址。（如果要核實，你可以嘗試給其他會員傳送一封郵件。） 管理員可能也要求通過給你傳送郵件才能完成你在論壇的註冊，因此請一定確認你所提供的郵箱位址是有效並且正在使用的郵箱。";
$a_lang['mysql']['faq']['faqtitle_5'] = "這個論壇使用了Cookies？";
$a_lang['mysql']['faq']['faqtext_5'] = "在論壇是否使用cookies是可選的，但是使用可能會提高你在本站的經驗值。Cookies主要用於字你上次訪問以來是否在主題或各個論壇內有新貼發表，或者當你離開後再次返回論壇時自動記錄你的資訊。<br /><p>當你註冊的時候，有一個選項“下次返回論壇時自動登入”供你選擇。它將通過cookie存儲你的用戶名和密碼保存到你的電腦上。如果你正在使用的是一台共用的電腦，例如在圖書館、學校或在網吧內，或者你你放心其他人可能會使用這台電腦，我們建議你就不要使用這個功能。</p><br /><p>論壇同樣提供你選項通過cookie來記錄你當前的session變數，確保你在訪問論壇時一直保持在登入狀態。如果你不通過cookie存儲這些資訊，論壇session資料會通過你點擊的鏈結來傳送。如果你的電腦是通過代理伺服器訪問互聯網，並且其他用戶也通過這個代理訪問同樣的鏈結的時候，當選擇不使用cookie可能會造成問題。</p>";
$a_lang['mysql']['faq']['faqtitle_6'] = "什麼是表情符號？";
$a_lang['mysql']['faq']['faqtext_6'] = "<p>表情符號是一個小圖示，你可以插入到你的帖子內容中表達你的情緒，是高興還是困惑等等。例如，如果你輸入的是一個諷刺意見，然而你所表達的僅僅“是一個玩笑”的意思，那你可以很簡單的插入一個“wink”符號。</p><br /><p>如果你使用過郵件或網上聊天系統，或許你對表情符號的概念已經司空見慣了。某幾個文字字元相互組合就可以轉換為一個表情符號。例如: <b>:) </b> 會被轉換為一個笑臉。解釋這個表情符號代碼，將你的腦袋向左轉看這個字元，你會發現 <b>:) </b> 變成了一雙眼睛和一張正在微笑的嘴。</p><br /><p>有關論壇可以使用的全部表情符號列表，請<a href=\"misc.php?do=icon\"><b>點擊這裏</b></a>。</p><br /><p>在某些情況下，你可能希望在你的文字內容中不要將文本自動轉換為表情符號。那當你發表一個新帖子的時候，可以看到一個核取方塊，允許你“禁用表情符號”。</p>";
$a_lang['mysql']['faq']['faqtitle_7'] = "如何清除我的 Cookies？";
$a_lang['mysql']['faq']['faqtext_7'] = "你可以點擊<a href=\"login.php?do=logout\">這裏</a>清除你在論壇內的全部cookie記錄。如果你再次返回論壇的時候仍在登入狀態中，你可能必須要通過手動刪除你的cookies。<br /><br /><br /><br />這是用於 Internet Explorer 5 的說明:<br /><br /><ol><br />	<li>關閉所有的 Internet Explorer 視窗。</li><br />	<li>點擊“開始”按鈕。</li><br />	<li>移動到“搜尋”上並從出現的菜單中點擊“檔案和檔案夾”。</li><br />	<li>在出現的新視窗中，在“內容文字”區域內，輸入論壇位址，注意不要帶“http://”以及“www.”部分。例如，如果論壇地址是“http://www.molyx.com/index.php”，你需要輸入“molyx.com”（不要帶引號）</li><br />	<li>在“搜尋檔案夾”對話方塊內，輸入“C:\Windows\Cookies\”（不要帶引號）並點擊“搜尋”</li><br />	<li>在完成搜尋後，選中所有檔案（點擊一個檔案，再按 CTRL+A）並將它們全部刪除（點擊“刪除”鍵或者使用 SHIFT+DEL 組合鍵）</li><br /></ol><br /><br />你的cookies現在已被全部刪除。你應該重新啟動電腦再次訪問論壇確認一下。";
$a_lang['mysql']['faq']['faqtitle_8'] = "如何在個人資料中更改我的資訊？";
$a_lang['mysql']['faq']['faqtext_8'] = "保持個人資料是最新的記錄是每個會員的責任。尤其要確保你的郵箱位址現在仍在使用。你可以在你的個人資料中更改任何專案，當然你的用戶名除外。一旦你註冊了你的用戶名，你將永遠使用它登入。如果有極特別情況，你可以請求管理員更改你的用戶名，但請給出一個充足的理由。<br /><br /><br /><br />通過 <a href=\"usercp.php?do=editprofile\">這裏</a> 編輯你的個人資料。";
$a_lang['mysql']['faq']['faqtitle_9'] = "什麼是個人簽名？";
$a_lang['mysql']['faq']['faqtext_9'] = "當你註冊以後，你就可以設定你自己的簽名。這些文本將出現在所有你所發表的帖子的下方，看起來有點像便簽的抬頭。<br /><br /><br /><br />如果管理員允許會員使用個人簽名，那麼在你所發表的任何帖子中都會出現是否顯示個人簽名的選項。如果你設定了一個簽名，那麼論壇會在你所發表的資訊中自動增加你的簽名。當你撰寫新的帖子時，你也可以不點選“顯示個人簽名”核取方塊，禁止在這個帖子中出現個人簽名。<br /><br /><br /><br />你可以在編輯你所發表過的帖子時重新選擇是否“顯示個人簽名”的選項來改變個人簽名在帖子中的狀態。<br /><br /><br /><br />你可以通過編輯你的個人資料設定你的個人簽名。";
$a_lang['mysql']['faq']['faqtitle_10'] = "我忘記了我的密碼，我要怎麼做？";
$a_lang['mysql']['faq']['faqtext_10'] = "如果你忘記了你的密碼，你可以在任何要求填入密碼的頁面點擊“忘了密碼”鏈結。<br /><br /><br />這時將會轉入一個頁面，在這裏你只要填入你註冊時使用的郵箱位址，你的密碼就會馬上自動傳送過去。";
$a_lang['mysql']['faq']['faqtitle_11'] = "如何在個人資料中增加自定義頭銜？";
$a_lang['mysql']['faq']['faqtext_11'] = "如果管理員允許使用自定義頭銜，你可以通過編輯你的個人資料指定一段文字，輸入的文字將會出現在自定義用戶頭銜中。";
$a_lang['mysql']['faq']['faqtitle_12'] = "如何在我的用戶名下方增加一個頭像？";
$a_lang['mysql']['faq']['faqtext_12'] = "這些小的圖片稱為頭像。這些圖片會出現在所有你所發表的帖子中你的用戶名下面。可以使用兩種方式選擇頭像：管理員預先提供的頭像和你自己上傳的頭像。<br /><br /><br /><br />如果管理員提供了一組頭像並且頭像功能可用的話，你可以選擇一個頭像用於描述你的個性。<br /><br /><br /><br />管理員也可能同樣允許使用自定義頭像，將允許你你你自己的電腦中上傳一個頭像。";
$a_lang['mysql']['faq']['faqtitle_13'] = "我如何在論壇使用搜尋功能？";
$a_lang['mysql']['faq']['faqtext_13'] = "<p>你可以通過用戶名，帖子內或主題中正確的關鍵字，通過日期，在指定的論壇內搜尋帖子。</p><br /><p>使用搜尋功能，請在頁面上方點擊“搜尋”鏈結。</p><br /><p>你可以在任何有搜尋許可權的論壇內搜尋 - 如果你沒有查看隱私論壇的許可權時，你將無法在這些論壇內執行搜尋。</p>";
$a_lang['mysql']['faq']['faqtitle_14'] = "我可以通過論壇給其他會員傳送郵件嗎？";
$a_lang['mysql']['faq']['faqtext_14'] = "<p>當然可以！給其他會員傳送一封郵件，你可以在<a href=\"memberlist.php?\"><b>會員列表</b></a>中搜尋任何你希望聯繫的會員，或者在任何其他會員所發表的帖子中點擊郵件圖示來給其他會員傳送聯繫郵件</p><br /><p>通常情況下會打開一個表單頁面，你可以在這裏輸入資訊內容。當你打完你的資訊內容後，點擊［傳送郵件］按鈕，你的郵件就會立刻傳送出去。出於隱私考慮，接收方的郵箱位址在傳送過程中不會顯示。</p><br /><p>注意，如果你無法找到一個會員的郵件鏈結，那麼有可能是管理員禁止了論壇郵件功能，或者這個會員不希望接受來自論壇的其他會員給他傳送郵件。</p><br /><p>另一個常用的郵件功能有，你可以將你認為你的好朋友會感興趣的頁面鏈結的位址通過郵件傳送給他。當你查看主題的時候，你可以在這個頁面中找到一個鏈結，可以允許你傳送一個簡短的說明。你的推薦id會出現在你傳送的資訊的鏈結中，因此如果你的朋友通過你所傳送的鏈結查看註冊論壇的話，你的推薦總人數將會被自動記錄！</p><br /><p>已註冊的會員也可以使用<a href=\"private.php?\">短消息系統</a>給其他會員傳送私人資訊。</p>";
$a_lang['mysql']['faq']['faqtitle_15'] = "什麼是短消息？";
$a_lang['mysql']['faq']['faqtext_15'] = "<p>如果管理員允許使用<a href=\"private.php?\"><b>短消息</b></a>系統，已註冊會員就可以給其他會員傳送短消息。</p><br /><p><b>傳送短消息</b></p><br /><p>短消息的工作方式有點像郵件系統，但是僅限於論壇的註冊會員才能使用。你可以在你傳送的短消息中使用BBCODE代碼，表情符號和貼圖。</p><br /><p>你可以點擊控制面板中短消息內的“<a href=\"private.php?do=newpm\"><b>撰寫新短消息</b></a>”鏈結給論壇會員傳送一條短消息，或者點擊在會員發表的帖子內的短消息圖示來傳送短消息。</p><br /><p>在你傳送短消息的時候，你可以選擇保存一個副本在你的發件箱檔案夾內。</p><br /><p><b>短消息檔案夾</b></p><br /><p>默認狀態下，你在短消息內有兩個檔案夾可供使用，它們是收件箱和發件箱。</p><br /><p><a href=\"private.php?\"><b>收件箱</b></a>檔案夾包含了任何你收取的資訊，你可以在這裏查看所有你收到的資訊內容，連同給你傳送私人資訊的會員名，以及私人資訊的傳送時間和日期。</p><br /><p>The <a href=\"private.php?folderid=-1\"><b>發件箱</b></a>檔案夾包含了所有你傳送的短消息的副本，你所指定的需要保留副本的資訊保留在這裏以備將來使用。</p><br /><p>你可以點擊“<a href=\"private.php?do=editfolders\"><b>編輯檔案夾</b></a>”鏈結創建一個新的用於短消息的檔案夾。</p><br /><p>每一個檔案夾都允許你控制所選擇的不同短消息，可以將它們移動到你自定義的檔案夾內，或者將它們完全刪除。</p><br /><p>管理員或許限定了你的檔案夾內可保留的短消息存儲數量，因此你需要定時刪除一些舊的短消息。如果你的短消息數量超出了管理員限定數量，在你刪除舊的短消息以前，你將無法傳送和收取短消息。</p><br /><p>在你閱讀短消息的時候，你可以隨時回覆這條短消息，或者將這條短消息轉發給其他會員。你也可以將這條消息轉發給好友列表中的多個會員。</p><br /><p><b>短消息跟蹤</b></p><br /><p>當你傳送一條新的短消息的時候，你可能需要收取這條消息的閱讀回執。你可以通過<a href=\"private.php?do=showtrack\"><b>私人資訊跟蹤</b></a>頁面檢查你所傳送的資訊是否被接收方閱讀。</p><br /><p>這個頁面分為兩個部分：未閱讀的短消息和已閱讀的短消息。</p><br /><p><b>未閱讀的短消息</b>部分顯示的所有資訊表示你已經發出了閱讀回執請求，然而接收方還沒有閱讀這些資訊。接收方在論壇中的最後活動時間也將被顯示。如果你認為這些資訊在最近一段時間內不會被閱讀，或者有其他原因的話，此部分的資訊也可以取消傳送。如果管理員允許此功能，被取消的私人資訊也可以隨時被啟動。</p><br /><p><b>已閱讀的短消息</b>部分顯示的所有資訊表示你所發出了閱讀回執請求已被閱讀且已從接收方確認。短消息的閱讀時間也將被顯示。</p><br /><p>你可以通過選擇一些短消息並點擊［結束跟蹤］按鈕來將結束跟蹤任何短消息。</p>";
$a_lang['mysql']['faq']['faqtitle_16'] = "如何使用會員列表？";
$a_lang['mysql']['faq']['faqtext_16'] = "<p><a href=\"memberlist.php?\"><b>會員列表</b></a>包含了論壇中的所有已註冊會員。你可以按照用戶名的字母順序，會員註冊時間，或者按照會員的發帖數量來查看會員列表。</p><br /><p>會員列表中也可以使用<a href=\"memberlist.php?do=search\"><b>搜尋功能</b></a>，可以按照你所指定的範圍內快速定位會員記錄，例如搜尋在過去一周內新註冊的所有會員等等。</p>";
$a_lang['mysql']['faq']['faqtitle_17'] = "什麼是公告？";
$a_lang['mysql']['faq']['faqtext_17'] = "<p>公告是由管理員或版主所發表的特殊資訊。這個只是單方面給用戶傳達論壇通知。由於你無法回覆公告內容，如果你希望參與公告的討論，你可以在論壇內創建一個新的主題。</p>";
$a_lang['mysql']['faq']['faqtitle_18'] = "我可以在帖子和資訊中使用指定的代碼或標籤嗎？";
$a_lang['mysql']['faq']['faqtext_18'] = "<p>在多數情況下，你的帖子可能只包含純文本，但在一些特殊時候，你可能需要強調某些單詞或者使用代碼來定義（例如粗體字或斜體字）。</p><br /><p>依據論壇規定，你可以使用HTML語法來實現這些效果。然而，更多的時候這些是被禁止的，管理員可能會禁止使用HTML代碼，而僅可以使用BBCode代碼：這是一個特別的標籤系統，你可以用它來創建出大多數的文字效果。BBCode代碼可以非常方便的使用，而且可以避免惡意腳本的使用，並且不會打亂頁面佈局，因而更有優勢。</p><br /><p>你可以搜尋是否論壇允許使用<b>表情符號</b>，使用表情符號可以表達你的情緒，以及<b>貼圖代碼[img]</b>，允許你在資訊中增加圖片。</p><br /><p>有關BBCode代碼的更多資訊，<a href=\"misc.php?do=bbcode\"><b>點擊這裏</b></a>。</p>";
$a_lang['mysql']['faq']['faqtitle_19'] = "如何創建和參與投票？";
$a_lang['mysql']['faq']['faqtext_19'] = "<p>你可能注意到了論壇中有一些主題內還包含了一個可以參與投票的問題部分。這些主題稱之為“投票”並按照下列方式創建的:</p><br /><p><b>創建一個新投票</b></p><br /><p>當你發表一個新主題的時候，你可以使用創建一個投票的選項。</p><br /><p>這個功能允許你提出一個問題，並設定一些可能的答案。其他會員可以通過備選的答案參與投票，投票結果會被顯示在這個主題內。</p><br /><p>這是一個投票的例子:</p><br /><blockquote><br />  <p>你喜愛的顏色是哪個？</p><br />  <ol><br />    <li>紅色</li><br />    <li>藍色</li><br />    <li>黃色</li><br />    <li>綠色</li><br />    <li>帶黃點的天藍色</li><br />  </ol><br /></blockquote><br /><p>只有在你發表新主題的時候才能創建投票，只需要點選頁面下方的“是！我要發表投票”核取方塊，並設定好你準備包括的答案數量就可以了。</p><br /><p>當你點擊送出按鈕後，你將會轉到投票創建頁面，在這裏你可以提出問題，並在答案列表中寫入你準備包括的答案。</p><br /><p>你也可以指定一個用於這個投票的時限，比如將投票進行一個星期就停止投票。</p><br /><b>參與投票並查看投票結果</b><br /><p>參與一個投票，只需要選擇你希望投票的選項，並點擊［投票］按鈕。你可以在你投票前點擊“查看結果”鏈結查看當前這個投票的結果。是否參與投票是完全可選的，你可以選擇任何一個選項參與投票或者根本不投票。</p><br /><p>通常情況下，你參與了一個投票後就不能對這個投票再次投票了，因此在你投票前請慎重考慮！</p>";
$a_lang['mysql']['faq']['faqtitle_20'] = "什麼是多重引用？";
$a_lang['mysql']['faq']['faqtext_20'] = "<p>多用引用是為了能更方便的與會員進行交流而設計的一套引用系統，你可以很方便的在同一個主題內答復多位元會員發表的主題</p><br /><p>你只需要在主題頁面將\"引用\"按鈕選為高亮狀態就可以通過頁面中的任何回覆按鈕，或者直接通過頁面下方的快速回覆框輸入資訊來回覆多人的話題。</p>";
$a_lang['mysql']['faq']['faqtitle_21'] = "什麼是附件？";
$a_lang['mysql']['faq']['faqtext_21'] = "<p>管理員可能允許你使用上傳附件的功能，允許你在帖子中上傳一些檔案。它可以是一個圖片，一個文本文檔，一個壓縮檔案等等。論壇上傳的附件並不一定支援你硬碟中的檔案類型！</p><br /><p>在一個新的帖子中上傳一個檔案，只需要選擇好你電腦內的附件，並點擊上傳按鈕就可以上傳完成一個附件。</p><br /><p>在發貼之後，附件會顯示在你所發表的資訊中。查看附件內容（如果沒有被直接顯示），只需要點擊在附件圖示後的檔案名鏈結就可以了。</p>";
$a_lang['mysql']['faq']['faqtitle_22'] = "我可以編輯自己的帖子嗎？";
$a_lang['mysql']['faq']['faqtext_22'] = "<p>如果你已經註冊，你就可以編輯和刪除你的帖子。但請注意管理員按照自己的意願決定是否禁止這個功能。你編輯帖子可能受到時間限制，這些取決於管理員對論壇的設定。</p><br /><p>編輯或者刪除你的帖子，在你想編輯的帖子中點擊\"編輯\"圖示。</p><br /><p>在你完成修改以後，可能會出現一個注釋，用於告知其他會員你已經編輯過你的帖子。管理員和版主可能不會受這個條件的限制，而不會出現這個注釋。</p>";
$a_lang['mysql']['faq']['faqtitle_23'] = "什麼是標題圖示？";
$a_lang['mysql']['faq']['faqtext_23'] = "<p>管理員可能允許在主題、帖子和私人資訊中使用標題圖示。標題圖示允許你指定一個小圖示隨帖子一同發表，使用它可以直接表達你這個帖子所表達的情緒。</p>";
$a_lang['mysql']['faq']['faqtitle_24'] = "什麼是版主？";
$a_lang['mysql']['faq']['faqtext_24'] = "<p>版主負責監控指定論壇中資訊內容。通常可以編輯和刪除帖子，移動主題，並處理其他事務。一個論壇的版主通常對會員而言可以有明顯的幫助而並對他所管理的論壇內容有獨到的見解。</p>";
$a_lang['mysql']['faq']['faqtitle_25'] = "為什麼在我的帖子中有一些單詞不會顯示？";
$a_lang['mysql']['faq']['faqtext_25'] = "<p>管理員會對某些單詞進行過濾。如果你的帖子中包含了這些被過濾的單詞，這部分內容就會變為這樣: ****。</p><br /><p>這些單詞過濾對所有用戶都適用，電腦會自動搜尋並替換那些單詞為替代的文字。但這種過濾並不精確。</p>";
$a_lang['mysql']['faq']['faqtitle_26'] = "積分策略擴展";
$a_lang['mysql']['faq']['faqtitle_27'] = "什麼是積分策略擴展？";
$a_lang['mysql']['faq']['faqtext_27'] = "積分策略擴展是論壇的對用戶貢獻度的一種擴充管理手段。當用戶在“發佈新主題”，“回覆帖子”，“上傳或下載附件”，“獲得精華主題評分及獲得勳章”，“傳送短消息”時自動根據管理員設定的相關參數而得到的相關附加用戶參數。這個參數不但表明了用戶對論壇的相關貢獻度大小，而且，一定的參數下限會影響到用戶使用論壇的一些相關模組的許可權。";
$a_lang['mysql']['faq']['faqtitle_28'] = "當前論壇設定了哪些積分擴展模組？";
$a_lang['mysql']['faq']['faqtext_28'] = "論壇管理員已設定了以下模組用於用戶積分擴展設定：<br /><br /><#show_credit#><br /><br />說明：<br />如果該參數為正數，則用戶在執行相關操作時，會相應對此設定的數值進行累加。<br />如果該參數為負數，則用戶在執行相關操作時，會相應對此設定的數值進行減法操作。<br />如果該參數不存在，則用戶所做操作對此積分模組不存在影響。<br />如果用戶的某積分達到管理員設定的積分下限，則相應涉及到減法操作的項目將無法完成。";
$a_lang['mysql']['faq']['faqtitle_29'] = "為什麼我的一些操作無法執行？";
$a_lang['mysql']['faq']['faqtext_29'] = "如果你的積分擴展參數低於管理員設定的某些功能限定時，那麼可能你的一些相關操作將被限制。直到你的這個積分值高於管理員設定的標準才可以繼續執行這個操作。";

$a_lang['mysql']['forum']['testsort'] = "測試分類";
$a_lang['mysql']['forum']['testforum'] = "測試分區";
$a_lang['mysql']['forum']['testdesc'] = "默認安裝板塊";

$a_lang['mysql']['league']['molyxteam'] = "魔力論壇 MolyX Board";
$a_lang['mysql']['league']['molyxdesc'] = "魔力論壇魔力體驗 - MolyX Magic Experience";
$a_lang['mysql']['league']['hogesoftitle'] = "厚建軟件 HOGE Software";
$a_lang['mysql']['league']['hogesofdesc'] = "創新凸顯實力 - 我們的產品體系 LivCMS / MolyX Board / LivSearch / LivBlog";

$a_lang['mysql']['setting']['uploadurl'] = "上傳檔案的URL地址";
$a_lang['mysql']['setting']['uploadurldesc'] = "你的上傳檔案夾的URL地址";
$a_lang['mysql']['setting']['uploadfolder'] = "上傳檔案夾的路徑";
$a_lang['mysql']['setting']['uploadfolderdesc'] = "用於存放上傳檔案的絕對路徑，注意不是URL鏈結。";
$a_lang['mysql']['setting']['remoteattach'] = "遠端附件URL位址";
$a_lang['mysql']['setting']['remoteattachdesc'] = "如果設定此選項，則此論壇作為鏡像伺服器使用，用戶無法通過此論壇上傳附件。請注意關閉主伺服器的計畫任務更改附件檔案夾位址功能";
$a_lang['mysql']['setting']['headerredirect'] = "自動跳轉方式";
$a_lang['mysql']['setting']['headerredirectdesc'] = "這個選項用於不使用跳轉頁面的轉向方式。請根據所使用的伺服器系統選擇最佳方式。";
$a_lang['mysql']['setting']['headerredirectextra'] = "location=location 方式 (*nix 系統)\nrefresh=Refresh 刷新 (Windows 系統)\nhtml=HTML META 跳轉 (如果以上方式失敗的話...)";
$a_lang['mysql']['setting']['removeredirect'] = "刪除全部轉向頁面鏈結？";
$a_lang['mysql']['setting']['removeredirectdesc'] = "如果設定為“是”的話，將會刪除所有跳轉頁面。";
$a_lang['mysql']['setting']['numberformat'] = "數位格式化方式";
$a_lang['mysql']['setting']['numberformatdesc'] = "你可以在這裏選擇一個用於千位元符的分割字元";
$a_lang['mysql']['setting']['numberformatextra'] = "none=不做格式化\n,=,\n.=.";
$a_lang['mysql']['setting']['gdversion'] = "GD 庫版本";
$a_lang['mysql']['setting']['gdversiondesc'] = "你的伺服器所安裝的GD庫版本。如果GD庫已安裝，你可以在phpinfo()資訊中發現。";
$a_lang['mysql']['setting']['isajax'] = "是否在全局使用AJAX技術";
$a_lang['mysql']['setting']['isajaxdesc'] = "如果使用AJAX技術的話，則用戶可以更方便的進行無刷新頁面操作，減少伺服器帶寬，但同時相應會對用戶流覽器增加部分負擔。";
$a_lang['mysql']['setting']['default_lang'] = "默認使用的語言包";
$a_lang['mysql']['setting']['default_langdesc'] = "默認用戶訪問網站使用的語言包";
$a_lang['mysql']['setting']['showtoday'] = "是否在頁面顯示當日發帖統計？";
$a_lang['mysql']['setting']['showtodaydesc'] = "如果使用的話，則前臺板塊及統計列表內會顯示當日的發帖數量";
$a_lang['mysql']['setting']['miibeian'] = "網站備案資訊代碼";
$a_lang['mysql']['setting']['miibeiandesc'] = "請在這裏填寫你的網站備案資訊ID。<br />詳細參考：<a href=\'http://www.miibeian.gov.cn\' target=\'_blank\'>信產部備案網站</a>";
$a_lang['mysql']['setting']['cookietimeout'] = "用戶線上超時時限 [單位: 分鐘]";
$a_lang['mysql']['setting']['loadlimit'] = "*NIX 系統負載限制";
$a_lang['mysql']['setting']['loadlimitdesc'] = "對於某些 *NIX 系統，可以通過這裏限制用戶訪問論壇，一旦伺服器超過了負載，其他用戶將禁止訪問論壇。<br />留空將不作限制";
$a_lang['mysql']['setting']['bbtitle'] = "論壇名稱";
$a_lang['mysql']['setting']['bbtitledesc'] = "你的論壇名稱。出現在每一頁的標題、導航菜單中。";
$a_lang['mysql']['setting']['bburl'] = "論壇地址";
$a_lang['mysql']['setting']['bburldesc'] = "你的論壇地址。出現在每一頁的標題、導航菜單中。";
$a_lang['mysql']['setting']['hometitle'] = "網站名稱";
$a_lang['mysql']['setting']['hometitledesc'] = "你的網站名稱。將出現在所有頁面的底部。";
$a_lang['mysql']['setting']['homeurl'] = "網站地址";
$a_lang['mysql']['setting']['homeurldesc'] = "你的網站地址。將出現在所有頁面的底部。";
$a_lang['mysql']['setting']['adminurl'] = "管理控制面板檔案夾";
$a_lang['mysql']['setting']['adminurldesc'] = "在這裏可以設定管理控制面板的檔案夾位址，可以使用相對檔案夾方式。注意結尾不要加反斜杠。更改此設定還需要手工在FTP中更改相應檔案夾。";
$a_lang['mysql']['setting']['redirecturl'] = "默認頁面跳轉位址";
$a_lang['mysql']['setting']['redirecturldesc'] = "當系統無法獲取要跳轉的頁面URL位址時，默認將程式跳轉到的位置。";
$a_lang['mysql']['setting']['redirecturlextra'] = "1=論壇首頁\n2=網站首頁";
$a_lang['mysql']['setting']['cookiedomain'] = "Cookie 作用域";
$a_lang['mysql']['setting']['cookiedomaindesc'] = "即你想使本論壇的cookie起作用的範圍。如果你想將此效果作用於你的網站“yourhost.com”，而不僅僅是“forums.yourhost.com”，那請在這裏輸入“.yourhost.com”(注意有兩個點！)。本項可以留空。";
$a_lang['mysql']['setting']['cookieprefix'] = "Cookie 首碼";
$a_lang['mysql']['setting']['cookieprefixdesc'] = "可以此設定在單一主機上安裝多個論壇。";
$a_lang['mysql']['setting']['cookiepath'] = "保存 Cookies 的路徑";
$a_lang['mysql']['setting']['cookiepathdesc'] = "保存cookies的路徑。如果在同一個功能變數名稱裏運行不止一個論壇，最好各個論壇設定不同的路徑。";
$a_lang['mysql']['setting']['gzipoutput'] = "開啟 GZIP 頁面壓縮輸出？";
$a_lang['mysql']['setting']['gzipoutputdesc'] = "選擇是將允許論壇通過 gzip 輸出頁面，可以很明顯的降低帶寬需求。但只有在用戶端支援的情況下才可使用，並且對 HTTP 1.1 相容，並會加大伺服器系統開銷。";
$a_lang['mysql']['setting']['timezoneoffset'] = "伺服器所在時區";
$a_lang['mysql']['setting']['timezoneoffsetdesc'] = "<span style=\'color:red\'>請在這裏正確的設定伺服器所在時區，如果設定正確但是出現了一個小時時差的話，說明伺服器啟用了夏令時設定，需要用戶自行在個人控制面板中修正。</span>";
$a_lang['mysql']['setting']['timeadjust'] = "伺服器時差調整 (單位: 分鐘)";
$a_lang['mysql']['setting']['timeadjustdesc'] = "你可以通過這個選項更精確地調節伺服器時間設定。如果伺服器時間過快的話，請在輸入的數位起始部分使用 \'-\' 號扣除相應時差。";
$a_lang['mysql']['setting']['standardtimeformat'] = "標準時間格式";
$a_lang['mysql']['setting']['standardtimeformatdesc'] = "查看更多參數: <a href=\'http://www.php.net/manual-lookup.php?function=date\' target=\'_blank\'>http://www.php.net/manual-lookup.php?function=date</a>";
$a_lang['mysql']['setting']['longtimeformat'] = "擴充的時間格式";
$a_lang['mysql']['setting']['longtimeformatdesc'] = "查看更多參數: <a href=\'http://www.php.net/manual-lookup.php?function=date\' target=\'_blank\'>http://www.php.net/manual-lookup.php?function=date</a>";
$a_lang['mysql']['setting']['registereddateformat'] = "註冊日期格式";
$a_lang['mysql']['setting']['registereddateformatdesc'] = "查看更多參數: <a href=\'http://www.php.net/manual-lookup.php?function=date\' target=\'_blank\'>http://www.php.net/manual-lookup.php?function=date</a>";
$a_lang['mysql']['setting']['allowselectstyles'] = "用戶可以選擇風格？";
$a_lang['mysql']['setting']['titlechangeposts'] = "用戶的發帖量達到多少才可以使用自定義頭銜？";
$a_lang['mysql']['setting']['titlechangepostsdesc'] = "對於可以使用自定義用戶頭銜的用戶組的限定值。留空將忽略此參數。";
$a_lang['mysql']['setting']['locationmaxlength'] = "用戶在“來自”部分允許輸入的最大字數";
$a_lang['mysql']['setting']['signaturemaxlength'] = "用戶在“個人簽名”部分允許輸入的最大字數";
$a_lang['mysql']['setting']['signatureallowhtml'] = "允許在簽名中使用HTML代碼？";
$a_lang['mysql']['setting']['signatureallowhtmldesc'] = "出於安全考慮，強烈建議你不要開啟此選項。";
$a_lang['mysql']['setting']['signatureallowbbcode'] = "允許在簽名中使用BBCODE代碼？";
$a_lang['mysql']['setting']['allowuploadsigimg'] = "允許從本地上傳圖片到簽名內？";
$a_lang['mysql']['setting']['sigimgdimension'] = "從本地上傳圖片的最大尺寸";
$a_lang['mysql']['setting']['sigimgdimensiondesc'] = "(寬度 <b>x</b> 高度)<br />超過此大小的圖片將自動縮放";
$a_lang['mysql']['setting']['removesubscibe'] = "自動刪除 x 天內沒有新回覆的訂閱主題";
$a_lang['mysql']['setting']['removesubscibedesc'] = "留空或輸入 0 將禁止自動刪除。";
$a_lang['mysql']['setting']['avatarsenabled'] = "允許用戶使用頭像？";
$a_lang['mysql']['setting']['defaultavatar'] = "默認頭像的檔案名";
$a_lang['mysql']['setting']['defaultavatardesc'] = "請將默認頭像放置在./images/avatars/檔案夾內。留空將不調用系統默認頭像。";
$a_lang['mysql']['setting']['avatarextension'] = "允許使用的頭像檔案副檔名";
$a_lang['mysql']['setting']['avatarextensiondesc'] = "請使用逗號分開每個副檔名。";
$a_lang['mysql']['setting']['avatarurl'] = "允許用戶頭像使用遠端URL鏈結？";
$a_lang['mysql']['setting']['avatamaxsize'] = "可上傳頭像的最大位元組數 (單位: KB)";
$a_lang['mysql']['setting']['avatardimension'] = "頭像的最大尺寸";
$a_lang['mysql']['setting']['avatardimensiondesc'] = "(寬度 <b>x</b> 高度)";
$a_lang['mysql']['setting']['avatardimensiondefault'] = "頭像庫的默認尺寸";
$a_lang['mysql']['setting']['avatardimensiondefaultdesc'] = "(寬度 <b>x</b> 高度)";
$a_lang['mysql']['setting']['avatarcolspannumbers'] = "頭像庫列表的列數";
$a_lang['mysql']['setting']['disableavatarsize'] = "禁止論壇將頭像自動縮放？";
$a_lang['mysql']['setting']['disableavatarsizedesc'] = "如果禁止，用戶頭像大小將不自動縮放。";
$a_lang['mysql']['setting']['guestviewsignature'] = "允許遊客查看會員簽名？";
$a_lang['mysql']['setting']['guestviewimg'] = "允許遊客直接查看帖子內的圖片？";
$a_lang['mysql']['setting']['guestviewavatar'] = "允許遊客查看用戶頭像？";
$a_lang['mysql']['setting']['award_deduct'] = "申請榮譽勳章花費的資金";
$a_lang['mysql']['setting']['award_deductdesc'] = "用戶每次申請頒發榮譽勳章所扣除的金錢及積分。請使用（金錢|積分）的方式設定參數。";
$a_lang['mysql']['setting']['maxpostchars'] = "每個帖子最大的字數";
$a_lang['mysql']['setting']['minpostchars'] = "每個帖子最小的字數";
$a_lang['mysql']['setting']['maxflashwidth'] = "FLASH 貼圖顯示的寬度 (單位: 圖元)";
$a_lang['mysql']['setting']['maxflashwidthdesc'] = "如果 [flash] 標籤開啟的情況下";
$a_lang['mysql']['setting']['maxflashheight'] = "FLASH 貼圖顯示的高度 (單位: 圖元)";
$a_lang['mysql']['setting']['maxflashheightdesc'] = "如果 [flash] 標籤開啟的情況下";
$a_lang['mysql']['setting']['perlineicons'] = "每行顯示的發帖圖示數量";
$a_lang['mysql']['setting']['rowsmiles'] = "在表情符號表單中顯示的表情符號行數";
$a_lang['mysql']['setting']['rowsmilesdesc'] = "這個表單顯示在在發帖頁面中。";
$a_lang['mysql']['setting']['perlinesmiles'] = "在表情符號表單中顯示的表情符號列數";
$a_lang['mysql']['setting']['perlinesmilesdesc'] = "這個表單顯示在在發帖頁面中。";
$a_lang['mysql']['setting']['stripquotes'] = "去除嵌入的引用訊息？";
$a_lang['mysql']['setting']['stripquotesdesc'] = "將刪除所有引用帖子中帶有引用標籤的內容。";
$a_lang['mysql']['setting']['imageextension'] = "合法的帖圖副檔名";
$a_lang['mysql']['setting']['imageextensiondesc'] = "定義在帖圖標籤 [img][/img] 可以使用的副檔名。\n<br />請用逗號分開每個名稱 (gif,jpeg,jpg)";
$a_lang['mysql']['setting']['guesttag'] = "遊客標記符號";
$a_lang['mysql']['setting']['guesttagdesc'] = "當遊客發帖的時候，在這裏設定用於遊客的標示名稱，以防止同註冊用戶名稱混淆";
$a_lang['mysql']['setting']['enablepolltags'] = "在投票中允許使用 [IMG] 和 [URL] 標籤？";
$a_lang['mysql']['setting']['maxpolloptions'] = "每個投票允許使用的最大結果數量";
$a_lang['mysql']['setting']['addpolltimeout'] = "在主題作者發表主題後多長時間內可以在主題內增加一個投票？";
$a_lang['mysql']['setting']['addpolltimeoutdesc'] = "對管理員及超級版主不起作用";
$a_lang['mysql']['setting']['disablenoreplypoll'] = "禁止會員發表 “僅為投票的主題” ？";
$a_lang['mysql']['setting']['floodchecktime'] = "防灌水控制 (單位: 秒)";
$a_lang['mysql']['setting']['floodchecktimedesc'] = "用戶在多少秒之後才可以再次發帖<br />留空將禁用灌水控制。";
$a_lang['mysql']['setting']['watermark'] = "開啟圖片浮水印功能";
$a_lang['mysql']['setting']['watermarkdesc'] = "是否在發帖時使用上傳附件浮水印功能。如果images根檔案夾下有 watermark.png 圖片的話，將優先使用圖片浮水印。";
$a_lang['mysql']['setting']['watermarkextra'] = "1=左上\n2=左下\n3=右上\n4=右下\n5=中間";
$a_lang['mysql']['setting']['markposition'] = "浮水印圖片出現的位置";
$a_lang['mysql']['setting']['markpositiondesc'] = "如果開啟了上面的浮水印功能，並且使用圖片浮水印的話，請在這裏設定圖片浮水印出現的位置。";
$a_lang['mysql']['setting']['useantispam'] = "使用驗證碼";
$a_lang['mysql']['setting']['useantispamdesc'] = "用戶在發帖時必須填寫驗證碼後才能正常發佈資訊，可以防止一些惡意灌水機的使用。";
$a_lang['mysql']['setting']['mxemode'] = "編輯器默認初始化模式";
$a_lang['mysql']['setting']['mxemodedesc'] = "如果用戶第一次登入，或Cookies未設定編輯器的時候，系統分配的默認編輯器為BBCODE模式還是WYSIWYG模式";
$a_lang['mysql']['setting']['matchbrowser'] = "驗證用戶流覽器？";
$a_lang['mysql']['setting']['matchbrowserdesc'] = "這個功能可以防止一些其他通過 Session 進行嘗試的惡意操作，但同一用戶在同一時間內將無法通過其他流覽器登入論壇。";
$a_lang['mysql']['setting']['allowdynimg'] = "允許在[IMG]標籤內使用動態URL鏈結？";
$a_lang['mysql']['setting']['allowdynimgdesc'] = "將此選項設定為“否”，如果圖像路徑包含動態URL位址(例如 ? 和 & 符號)時，[IMG]標籤將不做使用。這樣可以防止用戶使用一些惡意[IMG]標籤代碼。";
$a_lang['mysql']['setting']['allowimages'] = "允許使用[IMG]貼圖代碼？";
$a_lang['mysql']['setting']['allowimagesdesc'] = "如果設定此選項為“否”的話，用戶的貼圖將以鏈結形式顯示。";
$a_lang['mysql']['setting']['allowflash'] = "允許在頭像中使用 FLASH 標籤？";
$a_lang['mysql']['setting']['allowflashdesc'] = "由於 Flash 代碼內可以使用腳本語言，因此可能會造成一些不安全隱患，在你確認論壇絕對安全的情況下才可以啟用此功能。";
$a_lang['mysql']['setting']['forcelogin'] = "強制用戶登入後才能訪問論壇？";
$a_lang['mysql']['setting']['forcelogindesc'] = "如果此選項設定為“是”的話，遊客只有登入後才可以訪問論壇。";
$a_lang['mysql']['setting']['WOLenable'] = "允許用戶查看看誰線上列表？";
$a_lang['mysql']['setting']['enablesearches'] = "用戶可以使用搜尋功能？";
$a_lang['mysql']['setting']['minsearchlength'] = "搜尋關鍵字的最小長度";
$a_lang['mysql']['setting']['postsearchlength'] = "帖子搜尋顯示頁面將過長的帖子自動裁切所保留的字元數";
$a_lang['mysql']['setting']['postsearchlengthdesc'] = "任何超過此數值的搜尋結果都將被自動裁切。<br />留空將顯示全部帖子內容";
$a_lang['mysql']['setting']['forumindex'] = "論壇首頁名稱";
$a_lang['mysql']['setting']['forumindexdesc'] = "你可以在這裏設定論壇首頁的名稱，請注意，如果更改了此設定，請在FTP中更改為對應的檔案名稱。";
$a_lang['mysql']['setting']['shownewslink'] = "是否在論壇首頁顯示 “最新新聞” 的鏈結？";
$a_lang['mysql']['setting']['newsforumid'] = "用於顯示新聞的論壇";
$a_lang['mysql']['setting']['showloggedin'] = "在首頁顯示線上會員？";
$a_lang['mysql']['setting']['showstatus'] = "在首頁顯示論壇統計？";
$a_lang['mysql']['setting']['showbirthday'] = "在論壇首頁顯示當天過生日的會員？";
$a_lang['mysql']['setting']['showbirthdaydesc'] = "設定為“是”的話，將在論壇首頁顯示當天過生日的會員列表。";
$a_lang['mysql']['setting']['autohidebirthday'] = "當沒有過生日的會員的時候隱藏過生日的會員列表？";
$a_lang['mysql']['setting']['autohidebirthdaydesc'] = "如果設定為是的話，當上面的選項開啟，並且在當天沒沒有過生日的會員情況下，將隱藏這部分頁面。";
$a_lang['mysql']['setting']['maxonlineusers'] = "論壇列表狀態顯示的最大人數";
$a_lang['mysql']['setting']['maxonlineusersdesc'] = "如果論壇線上人數超過了此設定，將自動關閉線上列表詳細資料顯示。";
$a_lang['mysql']['setting']['showguest'] = "是否在線上列表內顯示遊客";
$a_lang['mysql']['setting']['showguestdesc'] = "如果開啟了這個選項，那麼在線上列表內將一併顯示遊客列表";
$a_lang['mysql']['setting']['birthday_send'] = "是否對當日生日用戶傳送祝賀信？";
$a_lang['mysql']['setting']['birthday_senddesc'] = "請在後邊的對話方塊內填寫生日祝賀信，此功能對資料庫負荷有一定影響，因此不建議10萬用戶以上論壇使用。<br />在文字內容中可以使用以下標籤:<br />{name}:用戶名; {money=xxx}:金錢; {reputation=xxx}:聲望; <br />如果使用了自定義積分策略，請使用 {唯一標籤=xxx} 的方式增加內容。<br />其中xxx是你希望給予的貨幣價值";
$a_lang['mysql']['setting']['birthday_send_type'] = "祝賀信傳送方式";
$a_lang['mysql']['setting']['birthday_send_typedesc'] = "使用哪種方式傳送用戶生日祝賀信";
$a_lang['mysql']['setting']['perpagepost'] = "在主題查看頁面用戶可選擇每頁顯示的帖子數量";
$a_lang['mysql']['setting']['perpagepostdesc'] = "請使用逗號分開每個數值。<br />例如: 5,15,20,25,30";
$a_lang['mysql']['setting']['maxposts'] = "主題查看頁面每頁顯示的帖子數";
$a_lang['mysql']['setting']['viewattachedimages'] = "在帖子中直接顯示上傳的圖片？";
$a_lang['mysql']['setting']['viewattachedimagesdesc'] = "如果設定為“是”的話，所有上傳的圖片都將在帖子中直接顯示。";
$a_lang['mysql']['setting']['viewattachedthumbs'] = "顯示附件圖片縮略圖？";
$a_lang['mysql']['setting']['viewattachedthumbsdesc'] = "如果上面的選項開啟並選擇此選項為“是”的話，附件圖片將以縮略圖方式顯示在帖子內，這樣做可以有效減少頁面輸出帶寬。";
$a_lang['mysql']['setting']['thumbswidth'] = "附件圖片縮略圖大小 [寬度]";
$a_lang['mysql']['setting']['thumbswidthdesc'] = "如果上面的選項開啟，你可以在這裏定義縮略圖的最大寬度。如果上傳的圖片小於此寬度的話，將不以縮略圖方式顯示。";
$a_lang['mysql']['setting']['thumbsheight'] = "附件圖片縮略圖大小 [高度]";
$a_lang['mysql']['setting']['thumbsheightdesc'] = "如果上面兩個選項都開啟的話，你可以在這裏定義縮略圖的最大高度。如果上傳的圖片小於此寬度的話，將不以縮略圖方式顯示。";
$a_lang['mysql']['setting']['allowviewresults'] = "允許用戶直接查看投票結果？";
$a_lang['mysql']['setting']['allowviewresultsdesc'] = "用戶可以在投票前查看當前投票的結果數量";
$a_lang['mysql']['setting']['onlyonesignatures'] = "每個主題頁面僅顯示一次會員簽名？";
$a_lang['mysql']['setting']['onlyonesignaturesdesc'] = "如果開啟了這個選項，則在同一個主題內，如果會員使用了簽名，並且發表了多個帖子的話，則每個頁面僅顯示一次簽名。";
$a_lang['mysql']['setting']['maxthreads'] = "每頁顯示的主題數量";
$a_lang['mysql']['setting']['gstickyprefix'] = "“總置頂主題” 的首碼";
$a_lang['mysql']['setting']['stickyprefix'] = "“置頂主題” 的首碼";
$a_lang['mysql']['setting']['movedprefix'] = "“移動主題” 的首碼";
$a_lang['mysql']['setting']['pollprefix'] = "“投票主題” 的首碼";
$a_lang['mysql']['setting']['hotnumberposts'] = "作為 “熱門主題” 的最低發帖數";
$a_lang['mysql']['setting']['showforumusers'] = "顯示 “正在流覽此論壇的會員” ？";
$a_lang['mysql']['setting']['showforumusersdesc'] = "如果開啟此項，將增加一次資料庫查詢";
$a_lang['mysql']['setting']['perpagethread'] = "在論壇列表頁面用戶可選擇每頁顯示的主題數量";
$a_lang['mysql']['setting']['perpagethreaddesc'] = "請使用逗號分開每個數值。<br />例如: 5,15,20,25,30";
$a_lang['mysql']['setting']['showsubforums'] = "顯示子論壇鏈結？";
$a_lang['mysql']['setting']['showsubforumsdesc'] = "是否在論壇列表內顯示子論壇鏈結";
$a_lang['mysql']['setting']['showmoderatorcolumn'] = "是否顯示版主列";
$a_lang['mysql']['setting']['showmoderatorcolumndesc'] = "在首頁、論壇顯示頁面和用戶控制面板頁面開啟或關閉顯示版主列。";
$a_lang['mysql']['setting']['stickopentag'] = "置頂主題修飾首碼";
$a_lang['mysql']['setting']['stickopentagdesc'] = "用於修飾置頂主題的HTML標籤首碼";
$a_lang['mysql']['setting']['stickclosetag'] = "置頂主題修飾尾碼";
$a_lang['mysql']['setting']['stickclosetagdesc'] = "用於修飾置頂主題的HTML標籤尾碼";
$a_lang['mysql']['setting']['threadpreview'] = "主題內容預覽方式";
$a_lang['mysql']['setting']['threadpreviewdesc'] = "是否在滑鼠移動到主題鏈結的時候查看主題內的帖子資訊？不建議用在訪問量很高的網站";
$a_lang['mysql']['setting']['showdescription'] = "開啟主題說明功能";
$a_lang['mysql']['setting']['showdescriptiondesc'] = "如果關閉主題說明功能，在主題列表內將不顯示主題說明選項";
$a_lang['mysql']['setting']['pmallowbbcode'] = "允許在短消息中使用 BBCODE 代碼？";
$a_lang['mysql']['setting']['pmallowhtml'] = "允許在短消息中使用 HTML 代碼？";
$a_lang['mysql']['setting']['pmallowhtmldesc'] = "如果設定為“是”的話，用戶可以在短消息中使用 HTML 代碼。出於安全考慮，強烈建議你不要開啟此選項。";
$a_lang['mysql']['setting']['emailreceived'] = "用於接收信件的郵箱位址";
$a_lang['mysql']['setting']['emailreceiveddesc'] = "此郵箱地址將出現在所有論壇郵件鏈結中。";
$a_lang['mysql']['setting']['emailsend'] = "用於傳送信件的郵箱地址";
$a_lang['mysql']['setting']['emailsenddesc'] = "將使用此郵箱傳送所有論壇郵件。";
$a_lang['mysql']['setting']['sesureemail'] = "使用安全表單傳送自論壇發出的郵件？";
$a_lang['mysql']['setting']['sesureemaildesc'] = "如果這個選項設定為“是”，那麼用戶必須使用線上填寫表單來給其他用戶傳送郵件，可以防止惡意收集會員郵件的程式。";
$a_lang['mysql']['setting']['emailtype'] = "郵件傳送方式";
$a_lang['mysql']['setting']['emailtypedesc'] = "如果 PHP 的 mail() 函數無法使用的話，可以選擇一個不使用用戶認證的郵局。如果你不清楚伺服器的配置，請與服務商聯繫。";
$a_lang['mysql']['setting']['smtphost'] = "SMTP 主機名稱";
$a_lang['mysql']['setting']['smtphostdesc'] = "預設值為 \'localhost\'";
$a_lang['mysql']['setting']['smtpport'] = "SMTP 埠";
$a_lang['mysql']['setting']['smtpportdesc'] = "預設值為 25";
$a_lang['mysql']['setting']['smtpuser'] = "SMTP 用戶名";
$a_lang['mysql']['setting']['smtpuserdesc'] = "在多數情況下，使用 \'localhost\' 不需增加此參數。";
$a_lang['mysql']['setting']['smtppassword'] = "SMTP 密碼";
$a_lang['mysql']['setting']['smtppassworddesc'] = "在多數情況下，使用 \'localhost\' 不需增加此參數。";
$a_lang['mysql']['setting']['emailwrapbracket'] = "在地址 \'from\' 和 \'to\' 中增加 \'&lt;\' 和 \'&gt;\' ？";
$a_lang['mysql']['setting']['emailwrapbracketdesc'] = "部分 SMTP 系統需要在郵件位址中增加 \'<\' address \'>\' (不帶引號) 的參數才能正常工作。如果你在傳送郵件的過程中出現了錯誤的話，請開啟這個選項。";
$a_lang['mysql']['setting']['disablereport'] = "禁用 “向版主報告此帖” 的功能？";
$a_lang['mysql']['setting']['disablereportdesc'] = "禁止用戶向版主反映有問題的帖子。";
$a_lang['mysql']['setting']['reporttype'] = "向版主報告帖子的方式";
$a_lang['mysql']['setting']['enablerecyclebin'] = "啟用回收站功能？";
$a_lang['mysql']['setting']['enablerecyclebindesc'] = "如果設定為“否”的話，此功能及下面的設定將不起作用。";
$a_lang['mysql']['setting']['recycleforumid'] = "指定作為回收站使用的論壇";
$a_lang['mysql']['setting']['recycleforumiddesc'] = "請將所設定的論壇關閉相應讀取許可權。";
$a_lang['mysql']['setting']['recycleforadmin'] = "對管理員使用回收站功能？";
$a_lang['mysql']['setting']['recycleforadmindesc'] = "如果設定為“否”的話，將在管理中直接刪除帖子和主題。";
$a_lang['mysql']['setting']['recycleforsuper'] = "對超級版主使用回收站功能？";
$a_lang['mysql']['setting']['recycleforsuperdesc'] = "如果設定為“否”的話，將在管理中直接刪除帖子和主題。";
$a_lang['mysql']['setting']['recycleformod'] = "對分論壇版主使用回收站功能？";
$a_lang['mysql']['setting']['recycleformoddesc'] = "如果設定為“否”的話，將在管理中直接刪除帖子和主題。";
$a_lang['mysql']['setting']['allowregistration'] = "允許新用戶註冊？";
$a_lang['mysql']['setting']['allowregistrationdesc'] = "如果此選項設定為“否”的話，任何嘗試註冊的行為均會被告知此時論壇已不接受新用戶註冊。";
$a_lang['mysql']['setting']['enableantispam'] = "開啟惡意註冊控制系統";
$a_lang['mysql']['setting']['enableantispamdesc'] = "為了防止某些惡意操作，開啟此選項將在用戶註冊時強制用戶輸入驗證碼。";
$a_lang['mysql']['setting']['moderatememberstype'] = "用戶註冊的驗證方式";
$a_lang['mysql']['setting']['moderatememberstypedesc'] = "通過管理員驗證新用戶註冊的資訊或者驗證用戶註冊的郵箱地址。";
$a_lang['mysql']['setting']['removemoderate'] = "自動刪除 x 天前未驗證的註冊資訊";
$a_lang['mysql']['setting']['removemoderatedesc'] = "將自動刪除你所指定的天數外仍未啟動的用戶資訊。輸入 0 將不刪除未啟動的帳號。";
$a_lang['mysql']['setting']['newregisterpost'] = "註冊後限制發帖時限";
$a_lang['mysql']['setting']['newregisterpostdesc'] = "對新註冊用戶，在註冊後 x 分鐘內才可以正常使用發帖功能。";
$a_lang['mysql']['setting']['registerrule'] = "註冊聲明";
$a_lang['mysql']['setting']['newuser_give'] = "新註冊用戶初始化給與的資金及積分";
$a_lang['mysql']['setting']['newuser_givedesc'] = "新註冊用戶初始化的資金及積分值。請使用（金錢|積分）的方式設定參數。";
$a_lang['mysql']['setting']['newuser_pm'] = "新註冊用戶的短消息歡迎資訊";
$a_lang['mysql']['setting']['newuser_pmdesc'] = "可以使用HTML代碼及BBCODE代碼";
$a_lang['mysql']['setting']['reg_ip_time'] = "同IP用戶註冊時限限制";
$a_lang['mysql']['setting']['reg_ip_timedesc'] = "在設定時間內，同IP需間隔以下時間才可以重複註冊;設定為0不限制。（單位: 分鐘）";
$a_lang['mysql']['setting']['showprivacy'] = "顯示隱私聲明的鏈結？";
$a_lang['mysql']['setting']['privacyurl'] = "隱私聲明調用的 http:// 鏈結位址";
$a_lang['mysql']['setting']['privacyurldesc'] = "如果你有單獨的隱私聲明頁面的話，請在這裏輸入隱私聲明的URL位址。";
$a_lang['mysql']['setting']['privacytitle'] = "隱私聲明的標題";
$a_lang['mysql']['setting']['privacytext'] = "如果未使用上面的鏈結位址的話，請在這裏輸入相關隱私聲明的文字。";
$a_lang['mysql']['setting']['privacytextdesc'] = "可以使用 HTML 代碼";
$a_lang['mysql']['setting']['bbactive'] = "論壇開放狀態？";
$a_lang['mysql']['setting']['bbactivedesc'] = "如果選擇“否”的話，將關閉論壇的開放狀態，僅對有許可權的用戶開放流覽。";
$a_lang['mysql']['setting']['bbclosedreason'] = "論壇關閉後顯示的資訊";
$a_lang['mysql']['setting']['openbank'] = "銀行開放狀態";
$a_lang['mysql']['setting']['openbankdesc'] = "是否開放銀行";
$a_lang['mysql']['setting']['bankcurrency'] = "貨幣單位";
$a_lang['mysql']['setting']['bankcurrencydesc'] = "用於計算貨幣的單位名稱。";
$a_lang['mysql']['setting']['bankcost'] = "開戶費用";
$a_lang['mysql']['setting']['bankcostdesc'] = "在銀行中開戶所需費用，現金不足者不能創建銀行帳戶。";
$a_lang['mysql']['setting']['bankinterest'] = "存款利率";
$a_lang['mysql']['setting']['bankinterestdesc'] = "銀行存款的日利率，當用戶處於貸款狀態時不計算利息。計算單位：&#8240;";
$a_lang['mysql']['setting']['bankexcost'] = "轉帳手續費";
$a_lang['mysql']['setting']['bankexcostdesc'] = "用戶之間轉帳收取的手續費。計算單位：&#8240;";
$a_lang['mysql']['setting']['bankexcostskip'] = "轉帳手續費補充";
$a_lang['mysql']['setting']['bankexcostskipdesc'] = "當一次性轉帳數額小於本設定值時，不收取轉帳手續費。";
$a_lang['mysql']['setting']['banknewthread'] = "發表新帖的獎勵";
$a_lang['mysql']['setting']['banknewthreaddesc'] = "用戶發表新帖時獎勵的金錢數量。";
$a_lang['mysql']['setting']['bankreplythread'] = "回覆帖子的獎勵";
$a_lang['mysql']['setting']['bankreplythreaddesc'] = "用戶回覆一個主題時獎勵的金錢數量。";
$a_lang['mysql']['setting']['bankquint'] = "設定為精華的獎勵";
$a_lang['mysql']['setting']['bankquintdesc'] = "當一個用戶的帖子被設定為“精華帖”時獎勵的金錢數量。";
$a_lang['mysql']['setting']['bankrepprice'] = "積分買入價";
$a_lang['mysql']['setting']['bankreppricedesc'] = "用戶以現金購買積分的價格。單位：元/1積分";
$a_lang['mysql']['setting']['bankrepsellprice'] = "積分賣出價";
$a_lang['mysql']['setting']['bankrepsellpricedesc'] = "用戶變賣積分為現金的價格。";
$a_lang['mysql']['setting']['bankloanonoff'] = "貸款功能";
$a_lang['mysql']['setting']['bankloanonoffdesc'] = "是否啟用貸款功能？";
$a_lang['mysql']['setting']['bankloanreglimit'] = "申請貸款的最低註冊時間";
$a_lang['mysql']['setting']['bankloanreglimitdesc'] = "會員自註冊成功多久後可以申請貸款。計算單位：小時";
$a_lang['mysql']['setting']['bankloanpostlimit'] = "申請貸款的最低發貼要求";
$a_lang['mysql']['setting']['bankloanpostlimitdesc'] = "會員需達到多少發貼量後方可申請貸款。";
$a_lang['mysql']['setting']['bankloanreplimit'] = "申請貸款的最低積分要求";
$a_lang['mysql']['setting']['bankloanreplimitdesc'] = "積分低於此設定的用戶不能申請貸款。";
$a_lang['mysql']['setting']['bankloanusegroup'] = "使用分組信譽機制";
$a_lang['mysql']['setting']['bankloanusegroupdesc'] = "根據不同用戶組設定相應信譽額上限。具體設定請到“用戶組管理”面板進行操作。";
$a_lang['mysql']['setting']['bankloanamount'] = "貸款信譽額";
$a_lang['mysql']['setting']['bankloanamountdesc'] = "每個用戶可以貸款的額度。在下列情況時此設定無效：1、選擇了“分組信譽機制”；2、遊客和等待驗證用戶沒有信譽額；";
$a_lang['mysql']['setting']['bankloantimelimit'] = "貸款償還期額";
$a_lang['mysql']['setting']['bankloantimelimitdesc'] = "自貸款當日起，直至償還貸款的時間限額，可用半形逗號提供用戶不同的貸款計畫，同時在“貸款利息”中填寫不同的貸款利率。計算單位：天";
$a_lang['mysql']['setting']['bankloaninterest'] = "貸款利息";
$a_lang['mysql']['setting']['bankloaninterestdesc'] = "償還貸款時所計算的利息，必須對應貸款期額分別寫出償款利率，否則將以第一個利率計算。計算單位：&#8240;";
$a_lang['mysql']['setting']['bankpbban'] = "破產封ID懲罰";
$a_lang['mysql']['setting']['bankpbbandesc'] = "如果用戶因為某些原因導致破產，則封禁ID作為懲罰。計算單位：天";
$a_lang['mysql']['setting']['bankpbrerate'] = "強制執行固定資產評估水準";
$a_lang['mysql']['setting']['bankpbreratedesc'] = "當用戶在償還貸款之日仍未償還，則由銀行進行強制執行。強制執行過程中，如用戶的資金總額不足以償還貸款和利息，則變賣所有固定資產進行償還。此設定為資產評估水準，即物品按市場價格的折價率。計算單位：%";
$a_lang['mysql']['setting']['bankpbreppanish'] = "強制執行的積分處罰";
$a_lang['mysql']['setting']['bankpbreppanishdesc'] = "如果用戶貸款被強制收回或資產被強制執行，扣除多少積分作為懲罰？";
$a_lang['mysql']['setting']['bankpbclean'] = "破產後銀行清產費用";
$a_lang['mysql']['setting']['bankpbcleandesc'] = "用戶破產後需要在銀行清產才能再次申請帳戶的費用。";
$a_lang['mysql']['setting']['reducetmoney'] = "刪除主題懲罰";
$a_lang['mysql']['setting']['reducetmoneydesc'] = "刪除一個主題扣除的金錢數量。";
$a_lang['mysql']['setting']['reducepmoney'] = "刪除帖子懲罰";
$a_lang['mysql']['setting']['reducepmoneydesc'] = "刪除一個帖子扣除的金錢數量。";
$a_lang['mysql']['setting']['version'] = "";
$a_lang['mysql']['setting']['openolrank'] = "開啟線上時長等級功能？";
$a_lang['mysql']['setting']['openolrankdesc'] = "是否開啟線上時長等級功能。如果選擇“否”，那麼對應的線上時長等級相關的功能將全部關閉。";
$a_lang['mysql']['setting']['olrankstart'] = "起步時長";
$a_lang['mysql']['setting']['olrankstartdesc'] = "線上時長等級第一級所需的時長（小時數）";
$a_lang['mysql']['setting']['olrankstep'] = "遞進時長";
$a_lang['mysql']['setting']['olrankstepdesc'] = "升級到下一級別比升級到此級別增加的時長。比如，如果遞進時長為5，升級到第1級需要10小時，升級到第2級則需要10+5=15小時，第3級需要20小時，以此類推。";
$a_lang['mysql']['setting']['isopeninvite'] = "是否打開邀請註冊";
$a_lang['mysql']['setting']['nolimitinviteusergroup'] = "選擇擁有無限邀請權的用戶組";
$a_lang['mysql']['setting']['nolimitinviteusergroupdesc'] = "按Shift或Ctrl選擇多個";
$a_lang['mysql']['setting']['limitinvitegroup'] = "選擇擁有限制邀請權的用戶組";
$a_lang['mysql']['setting']['limitinvitegroupdesc'] = "按Shift或Ctrl選擇多個";
$a_lang['mysql']['setting']['limitregtime'] = "用戶註冊時間達到";
$a_lang['mysql']['setting']['limitregtimedesc'] = "傳送無限邀請許可權此項不填（單位：天）";
$a_lang['mysql']['setting']['limitposttitlenum'] = "用戶發帖數達到";
$a_lang['mysql']['setting']['inviteminnum'] = "用戶最少可以有幾個邀請許可權";
$a_lang['mysql']['setting']['invitemaxnum'] = "用戶最多可以有幾個邀請許可權";
$a_lang['mysql']['setting']['invitexpiry'] = "具有限制邀請註冊許可權用戶的使用期限";
$a_lang['mysql']['setting']['inviteduserexpiry'] = "用戶發出邀請後幾天內註冊有效";
$a_lang['mysql']['setting']['timenotlogin'] = "僅對多長時間有登入的用戶發放";
$a_lang['mysql']['setting']['timenotlogindesc'] = "若用戶在設定時間之內沒登入過將不能得到該許可權（單位：天）";
$a_lang['mysql']['setting']['modreptype'] = "評分類型獎勵";
$a_lang['mysql']['setting']['modreptypedesc'] = "用戶組有權利給某些用戶獎勵或處罰,可以選擇加分或者加社區幣.";
$a_lang['mysql']['setting']['modrepmax'] = "社區幣獎勵限制金額";
$a_lang['mysql']['setting']['modrepmaxdesc'] = "獎勵會員的最大數額及最小數額,在設定該值的正負之間.";
$a_lang['mysql']['setting']['spider_roup'] = "對搜尋引擎Spider使用的用戶組";
$a_lang['mysql']['setting']['spider_roupdesc'] = "對於不開放遊客訪問的論壇而言，設定搜尋引擎蜘蛛訪問時的用戶組，可以更方便的讓搜尋引擎索引論壇資源";
$a_lang['mysql']['setting']['spiderid'] = "搜尋引擎BOT設定";
$a_lang['mysql']['setting']['spideriddesc'] = "請使用 | 分隔開每個BOT參數";
$a_lang['mysql']['setting']['mxemodeextra'] = "0=標準編輯器（bbcode）\r\n1=所見即所得編輯器";
$a_lang['mysql']['setting']['birthday_send_typeextra'] = "1=站內郵件和短消息\r\n2=短消息\r\n3=站內郵件";
$a_lang['mysql']['setting']['gstickyprefixdval'] = "總置頂: ";
$a_lang['mysql']['setting']['stickyprefixdval'] = "置頂: ";
$a_lang['mysql']['setting']['movedprefixdval'] = "移動: ";
$a_lang['mysql']['setting']['pollprefixdval'] = "投票: ";
$a_lang['mysql']['setting']['threadpreviewextra'] = "0=不使用主題預覽\r\n1=查看主題內容資訊\r\n2=查看最後回帖資訊";
$a_lang['mysql']['setting']['reporttypeextra'] = "email=郵件方式\r\npm=短消息";
$a_lang['mysql']['setting']['enableantispamextra'] = "0=關閉\r\ngd=高級方式 (需要 GD 庫支援)\r\ngif=標準方式 (無特別要求)";
$a_lang['mysql']['setting']['moderatememberstypextra'] = "user=驗證用戶的郵件\r\nadmin=管理員驗證帳號\r\n0=不需要驗證";
$a_lang['mysql']['setting']['registerruledval'] = "註冊聲明\r\n\r\n在這個論壇註冊是完全免費的！我們希望您遵守以下的論壇規定。如果你接受這個條件，請選中“我同意”對話方塊並點擊下面的“註冊”按鈕。如果你不想繼續註冊，點擊這裏返回論壇首頁。\r\n\r\n雖然{bbtitle}管理員和版主已經盡力避免所有令人討厭的資訊在此論壇出現，但仍無法顧及到論壇會員所發表的全部資訊。所有資訊均代表作者的觀點，{bbtitle}不對任何資訊內容所引發的爭議承擔責任。\r\n\r\n點擊同意按鈕，就表示你保證不會發佈任何有關政治、色情、宗教、迷信等違法資訊。\r\n\r\n{bbtitle}的管理人員有權在任何時刻移動、編輯、刪除、關閉任何主題。\r\n";
$a_lang['mysql']['setting']['bbclosedreasondval'] = "論壇調整中...";
$a_lang['mysql']['setting']['bankcurrencydval'] = "金幣";
$a_lang['mysql']['setting']['modreptypextra'] = "1=積分\r\n2=社區幣";
$a_lang['mysql']['setting']['adcolumns'] = "頁面廣告平排的列數";
$a_lang['mysql']['setting']['adcolumnsdesc'] = "超過設定值則自動換行";
$a_lang['mysql']['setting']['adinpost'] = "貼內廣告每頁顯示的條數";
$a_lang['mysql']['setting']['adinpostdesc'] = "設定主題每頁內顯示的廣告條數，超過設定條數的帖子將不顯示廣告，設置為 0 將在每個帖子內顯示廣告";
$a_lang['mysql']['settinggroup']['generalsetting'] = "常規設定";
$a_lang['mysql']['settinggroup']['generalsettingdesc'] = "有關論壇的訪問資訊、聯繫方式、論壇基本配置等常規資訊。";
$a_lang['mysql']['settinggroup']['forumoptimize'] = "論壇優化、節能處理";
$a_lang['mysql']['settinggroup']['forumoptimizedesc'] = "調整論壇性能等相關參數。";
$a_lang['mysql']['settinggroup']['sitenameurl'] = "站點名稱 / URL位址 / 聯繫資訊";
$a_lang['mysql']['settinggroup']['sitenameurldesc'] = "在這裏設定網站的基本資訊。";
$a_lang['mysql']['settinggroup']['cookieoption'] = "Cookies 和 HTTP header 輸出選項";
$a_lang['mysql']['settinggroup']['cookieoptiondesc'] = "調整Cookies的相關參數及伺服器頁面輸出設定。";
$a_lang['mysql']['settinggroup']['datetimeoption'] = "時間和日期選項";
$a_lang['mysql']['settinggroup']['datetimeoptiondesc'] = "論壇使用的時間及日期參數控制。";
$a_lang['mysql']['settinggroup']['userpara'] = "用戶參數";
$a_lang['mysql']['settinggroup']['userparadesc'] = "在這裏調整用戶的許可權及其它參數。";
$a_lang['mysql']['settinggroup']['postoption'] = "發帖選項";
$a_lang['mysql']['settinggroup']['postoptiondesc'] = "在這裏控制發帖、閱讀主題及投票的參數。";
$a_lang['mysql']['settinggroup']['securityctrl'] = "安全 &amp; 隱私控制";
$a_lang['mysql']['settinggroup']['securityctrldesc'] = "在這裏調整論壇的安全及隱私的相關參數。";
$a_lang['mysql']['settinggroup']['searchoption'] = "搜尋選項";
$a_lang['mysql']['settinggroup']['indexsetting'] = "論壇首頁設定";
$a_lang['mysql']['settinggroup']['indexsettingdesc'] = "在這裏指定用於顯示論壇新聞的論壇ID";
$a_lang['mysql']['settinggroup']['showthread'] = "主題顯示選項[showthread.php]";
$a_lang['mysql']['settinggroup']['forumdisplay'] = "論壇顯示選項[forumdisplay.php]";
$a_lang['mysql']['settinggroup']['emailpmsetting'] = "郵件 &amp; 短消息設定";
$a_lang['mysql']['settinggroup']['emailpmsettingdesc'] = "在這裏設定短消息和傳送郵件的相關參數。";
$a_lang['mysql']['settinggroup']['recyclesetting'] = "回收站設定";
$a_lang['mysql']['settinggroup']['recyclesettingdesc'] = "在這裏指定用於將待刪除主題所移動的論壇ID位置。";
$a_lang['mysql']['settinggroup']['userregoption'] = "用戶註冊選項";
$a_lang['mysql']['settinggroup']['privacyance'] = "隱私聲明";
$a_lang['mysql']['settinggroup']['privacyancedesc'] = "你可以在這裏設定論壇隱私聲明部分。如果開啟此設定，將會在頁面出現隱私聲明鏈結。";
$a_lang['mysql']['settinggroup']['opencloseforum'] = "開放或關閉論壇";
$a_lang['mysql']['settinggroup']['opencloseforumdesc'] = "在這裏設定論壇關閉/開啟狀態。";
$a_lang['mysql']['settinggroup']['olranksetting'] = "線上時長等級設定";
$a_lang['mysql']['settinggroup']['olranksettingdesc'] = "統計用戶線上時間長短，同時進行相應的等級判定。這裏是一些相關的設定。";
$a_lang['mysql']['settinggroup']['invitesetting'] = "邀請註冊條件設定";
$a_lang['mysql']['settinggroup']['invitesettingdesc'] = "設定用戶具有邀請註冊許可權的條件。";
$a_lang['mysql']['settinggroup']['searchenginesetting'] = "搜尋引擎設定";
$a_lang['mysql']['settinggroup']['searchenginesettingdesc'] = "在這裏設定搜尋引擎 Spider 相關參數";
$a_lang['mysql']['settinggroup']['adsetting'] = "廣告中心設定";
$a_lang['mysql']['settinggroup']['adsettingdesc'] = "在這裏設定廣告中心的相關參數";

$a_lang['mysql']['usergroup']['waittingvalidate'] = "等待驗證的會員";
$a_lang['mysql']['usergroup']['guest'] = "遊客";
$a_lang['mysql']['usergroup']['regmember'] = "註冊會員";
$a_lang['mysql']['usergroup']['admin'] = "管理員";
$a_lang['mysql']['usergroup']['banuser'] = "被封禁會員";
$a_lang['mysql']['usergroup']['supermod'] = "超級版主";
$a_lang['mysql']['usergroup']['mod'] = "版主";

$a_lang['mysql']['usertitle']['newuser'] = "新手上路";
$a_lang['mysql']['usertitle']['mediatemember'] = "中級會員";
$a_lang['mysql']['usertitle']['highermember'] = "高級會員";

// add 2.6.0
$a_lang['mysql']['setting']['usernameminlength'] = '用戶名最小子字數';
$a_lang['mysql']['setting']['usernameminlengthdesc'] = '註冊時輸入的用戶名必須達到的最小長度';
$a_lang['mysql']['setting']['usernamemaxlength'] = '用戶名最大字數';
$a_lang['mysql']['setting']['usernamemaxlengthdesc'] = '註冊時輸入的用戶名的最大長度（不要超過20）';
$a_lang['mysql']['setting']['moderatorlist'] = '版主顯示方式';
$a_lang['mysql']['setting']['moderatorlistd'] = '下拉菜單';
$a_lang['mysql']['setting']['moderatorlisth'] = '平面顯示';
$a_lang['mysql']['setting']['quickeditorloadmode'] = '快速回復編輯器載入模式';
$a_lang['mysql']['setting']['quickeditorloadmodedesc'] = '快速回復編輯器以何種方式載入。';
$a_lang['mysql']['setting']['quickeditorloadmodeextra'] = "1=直接載入\r\n2=點擊后載入";
$a_lang['mysql']['setting']['quickeditordisplaymenu'] = '快速回復編輯器是否顯示菜單';
$a_lang['mysql']['setting']['quickeditordisplaymenudesc'] = '快速回復編輯器是否顯示上排操作按鈕。設為“否”可以加快編輯器載入速度。';
$a_lang['install']['selectlanguage'] = '請選擇語言';
$a_lang['mysql']['setting']['guest'] = '未註冊用戶';
$a_lang['install']['welcome'] = '歡迎使用 MolyX Board 安裝腳本!';

// add 2.6.1
$a_lang['mysql']['setting']['rewritestatus'] = 'URL 靜態化';
$a_lang['mysql']['setting']['rewritestatusdesc'] = '選擇“是”將對常用頁面進行 URL 靜態化轉換，以提高搜索引擎抓取，本功能需要 Web 伺服器打開 URLRewrite 功能，因此需要伺服器許可權才可使用，相應規則請參考<a href="http://www.molyx.cn/index.php/%E8%AF%A6%E7%BB%86%E5%B8%B8%E8%A7%84%E8%AE%BE%E7%BD%AE#.E6.90.9C.E7.B4.A2.E5.BC.95.E6.93.8E.E8.AE.BE.E5.AE.9A" target="_blank">《用戶使用說明書》</a>。注意: 當訪問量很大時，本功能會輕微加重伺服器負擔。';
$a_lang['mysql']['setting']['threadviewsdelay'] = '主題查看數量延遲更新';
$a_lang['mysql']['setting']['threadviewsdelaydesc'] = '選擇“是”，將每過一個小時（實際時間以計畫任務“更新主題查看數量”的設置為准）更新一次主題查看數量。<br />如果您的論壇訪問量很大，建議開啟本功能以降低伺服器負擔。';
$a_lang['mysql']['setting']['attachmentviewsdelay'] = '附件查看數量延遲更新';
$a_lang['mysql']['setting']['attachmentviewsdelaydesc'] = '選擇“是”，將每過一個小時（實際時間以計畫任務“更新附件查看數量”的設置為准）更新一次附件查看數量。<br />如果您的論壇有很多的附件，特別是插入帖子中的圖片附件，建議開啟本功能以降低伺服器負擔。';
$a_lang['mysql']['cron']['threadviews'] = '更新主題查看數量';
$a_lang['mysql']['cron']['threadviewsdesc'] = '每小時更新主題查看數量，打開“主題查看數量延遲更新”後才會執行';
$a_lang['mysql']['cron']['attachmentviews'] = '更新附件查看數量';
$a_lang['mysql']['cron']['attachmentviewsdesc'] = '每小時更新附件查看數量，打開“附件查看數量延遲更新”後才會執行';

?>