<?php

$lang = array (
	'sell'				=>	"转让",
	'sell_descrip'		=>	"[b]{$log[username]}[/b] 转让装备： [b]{$log[toolname]}[/b] ,数量：{$log[nums]}。",
	'buy'				=>	"购买",
	'buy_descrip'		=>	"[b]{$log[username]}[/b] 向系统购买装备： [b]{$log[toolname]}[/b] ,数量：{$log[nums]},花费：{$log[money]}。",
	'buyuser_descrip'	=>	"[b]{$log[username]}[/b] 向[b]{$log[from]}[/b]购买装备： [b]{$log[toolname]}[/b] ,数量：{$log[nums]},花费：{$log[money]}。",
	'buyself_descrip'	=>	"[b]{$log[username]}[/b] 购回自己转让的装备： [b]{$log[toolname]}[/b] ,数量：{$log[nums]}",
	'change'			=>	"转换",
	'change_descrip_1'	=>	"[b]{$log[username]}[/b] 使用[b]交易币转换[/b]功能，获得 {$log[creditinfo]}，总计花费交易币数：{$log[currency]}",
	'change_descrip_2'	=>	"[b]{$log[username]}[/b] 使用[b]交易币转换[/b]功能，转换 $log[creditinfo] 为交易币，总共获得交易币：$log[currency]",
	'use'				=>	"使用",
	'tool_1_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将负威望转为 0。",
	'tool_2_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将所有负积分转为 0。",
	'tool_3_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 加亮显示。",
	'tool_4_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 在版块中置顶。",
	'tool_5_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 在所在分类中置顶。",
	'tool_6_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 在整个论坛中置顶。",
	'tool_7_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 提前到该版块首页。",
	'tool_8_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将自己在论坛的用户名改为[b]{$log[newname]}[/b]。",
	'tool_9_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 加为精华I。",
	'tool_10_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 加为精华II。",
	'tool_11_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 锁定。",
	'tool_12_descrip'	=>	"[b]{$log[username]}[/b] 使用装备 [b]{$log[toolname]}[/b] ,将帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 解除锁定。",
	'olpay'				=>	"充值",
	'olpay_descrip'		=>	"[b]{$log[username]}[/b] 使用交易币充值功能，充值金额：{$log[number]}，获得交易币：{$log[currency]}",
	'colony'			=>	"建群",
	'colony_descrip'	=>	"[b]{$log[username]}[/b] 使用创建群功能创建群[b]{$log[cname]}[/b]，总共花费交易币：{$log[currency]}。",
	'join'				=>	"加群",
	'join_descrip'		=>	"[b]{$log[username]}[/b] 加入群[b]{$log[cname]}[/b]，花费交易币：{$log[currency]}。",
	'sign'				=>	'签名',
	'sign_descrip'		=>	"[b]{$log[username]}[/b] 使用签名展示功能，花费交易币：{$log[currency]}。",
	'vire'				=>	'转帐',
	'vire_descrip'		=>	"[b]{$log[username]}[/b] 使用交易币转帐功能，给用户[b]{$log[toname]}[/b]转帐 {$log[currency]}交易币，系统收取手续费：{$log[tax]}。",
	'donate'			=> '捐献',
	'donate_descrip'	=> "[b]{$log[username]}[/b] 使用捐献给所在群($log[cname])捐献交易币：{$log[currency]}。",
	'cyvire_descrip'	=> "[b]{$log[username]}[/b] 使用群交易币管理功能，给用户[b]{$log[toname]}[/b]转帐 {$log[currency]}交易币，系统收取手续费：{$log[tax]}。",
	'group'				=> "用户组",
	'group_descrip'		=> "[b]{$log[username]}[/b] 使用用户组身份购买功能，购买用户组($log[gptitle])身份{$log[days]}天，总共花费交易币数：{$log[currency]}。",
);
?>