<?php

$lang = array (

'full_screen'						=> '全屏播放',
'bbcode_hide1'						=>"本部分设定了隐藏,您已回复过了,以下是隐藏的内容",
'bbcode_hide2'						=>"本部分内容设定了隐藏,需要回复后才能看到",
'bbcode_encode1'					=>"本部分内容设定了加密,查看此帖需要威望:",
'bbcode_encode2'					=>"您有足够的威望或权限浏览此文章,以下是加密内容:",
'bbcode_encode3'					=>"对不起!您没有登陆,请先<a href='login.php'><font color='red'>登录论坛</font></a>.",

'bbcode_sell_info'					=>"此贴售价 \$moneycost \$db_moneyname,已有 \$count 人购买",
'bbcode_sell_buy'					=>"购买人名单",
'bbcode_sell_submit'				=>"愿意购买,我买,我付钱",
'bbcode_sell_notice'	            => "<b>若发现会员采用欺骗的方法获取财富,请立刻举报,我们会对会员处以2-N倍的罚金,严重者封掉ID!</b>",
'seller'=>'<b>卖家：</b>',
'subject'=>'<b>商品名称：</b>',
'body'=>'<b>商品描述：</b>',
'price'=>'<b>商品价格：</b>',
'postage'=>'<b>邮费信息：</b>',
'postage_seller'=>'<b>邮费信息：</b>卖家承担邮费',
'contact'=>'<b>联系方式：</b>',
'demo'=>'<b>演示地址：</b>',
'ordinary_fee'=>'平邮：',
'express_fee'=>'快递：',

'size'=>'<b>软件大小：</b>',
'language'=>'<b>软件语言：</b>',
'type'=>'<b>软件类别：</b>',
'os'=>'<b>运行环境：</b>',
'date'=>'<b>更新时间：</b>',
'author'=>'<b>软件添加：</b>',
'level'=>'<b>软件评级：</b>',
'publish'=>'<b>开 发 商：</b>',
'preview'=>'<b>界面预览：</b>',
'hits'=>'<b>下载次数：</b>',
'descrip'=>'<b>软件简介：</b>',
'link'=>'<b>下载地址：</b>',
'shield_title'=>'该主题已屏蔽',
'shield_article'=>'该主题已被管理员屏蔽!',
'ban_article'=>'用户被禁言,该主题自动屏蔽!',
'rewarding'=>"此贴悬赏进行中...",
'reward_bestanswer'=>"最佳答案",
'reward_help'=>"热心助人",
'reward_hlp'=>"热心助人剩余点数",
'reward_cancle'=>"[结束悬赏]",
'reward_toadmin'=>"[联系版主]",
'reward_finished'=>"此贴悬赏结束",
'reward_author'=>"最佳答案获得者",
'reward_best_get'=>"最佳答案奖励",
'reward_help_get'=>"热心助人奖励",
'reward_manager'=>"[管理]",
'reward_title'=>"如果没有得到合适的答案,可以点此给斑主发短消息.经由斑主鉴定情况属实,可以返回最佳答案积分!",
'reward_msgtoadmin'=>"是否联系斑主,由斑主来处理?",
);
?>