<?php
$lang=array(

'operate_success'		=> "操作完成",
'have_login'			=> "您已经顺利登录",
'login_out'				=> "状态：您已经顺利退出网站",
'enter_thread'			=> "<a href=thread.php?fid=$fid>[ 发贴完毕点击进入主题列表 ]</a>",
'reg_success'			=> "恭喜您,完成注册现在可以开始使用您的会员权利了",
'mail_success'			=> "邮件发送完成",
'enter_c_thread'		=> "<a href=c_thread.php?fid=$fid>[ 发贴完毕点击进入主题列表 ]</a>",
'post_check'			=> "文章发表成功,本版块开启了发帖审核功能,请等待管理员审核!",
'masigle_ban_success'	=> "完成禁言,将自动跳转至会员资料页面",
'update_cache'			=> "正在更新会员排行缓存,请耐心等待!",
'colony_regsuccess'		=> "{$cn_name}注册成功，进入{$cn_name}基本资料设置",
'colony_joinsuccess'	=> "加入{$cn_name}成功,进入{$cn_name}首页。",
'colony_cardsuccess'	=> "{$cn_name}名片修改成功。",
'colony_postsuccess'	=> "发言成功。",
'colony_editsuccess'	=> "编辑成功。",
'colony_delsuccess'		=> "删除成功。",
'colony_quitsuccess'	=> "退出成功。",
'colony_setsuccess'		=> "{$cn_name}基本设置修改成功。",
'colony_cancelsuccess'	=> "{$cn_name}解散成功。",
'showsign_success'		=> "签名展示设置成功。",
'bank_savesuccess'		=> "完成存款!",
'bank_drawsuccess'		=> "完成取款!",
'bank_viresuccess'		=> "完成转帐!",
'bank_creditsuccess'	=> "完成积分转换!",
'blog_enterhomepage'	=> "进入 {$username} 的个人主页",
'friend_update_success'	=> "好友列表更新成功。",
'complete_list'			=> "该订单已完成支付。",
'bakup_step'			=>"正在备份数据库表 $t_name: 共 $rows 条记录，已经备份至 $c_n  条记录<br><br>已生成 $f_num 个备份文件，程序将自动备份余下部分",
'bakup_out'				=>"已全部备份,备份文件保存在data目录下，备份文件为<br>$bakfile",
'backup_data'           =>'论坛进入自动数据备份中，您将无法访问本论坛',
'group_buy_success'     =>'特殊组购买成功!!',
);
?>