<?php
$msg_add = "\n\n[b]文章：[/b][url=$db_bbsurl/read.php?tid=$msg[tid]]$msg[subject][/url]\n[b]发表日期：[/b]$msg[postdate]\n[b]所在版块：[/b][url=$db_bbsurl/thread.php?fid=$msg[fid]]$msg[forum][/url]\n[b]操作时间：[/b]{$msg[admindate]}\n[b]操作理由：[/b]$msg[reason]\n\n论坛管理操作通知短消息，对本次管理操作有任何异议，请与我取得联系。";

$lang = array (
	'olpay_title'=>'交易币充值支付成功.',
	'olpay_content'=>"交易币充值支付成功，您需要登录支付宝使用“[color=red]确认收货[/color]”功能完成本次交易。\n确认收货后系统会自动对您的交易币帐户进行充值。",
	'olpay_content_2'=>"交易币充值成功，本次充值金额：{$number}RMB，总共获得交易币个数：{$currency}。\n谢谢使用！",
	'virement_title'=>'银行汇款通知!!',
	'virement_content'=>"用户{$windid}通过银行给你转帐{$to_money}元钱，系统自动把以前的利息加到你的存款中，你的利息将从现在重新开始计算",

	'metal_add'=>'授予勋章通知',
	'metal_add_content'=>"您被授予勋章\n\n勋章名称：{$_MEDALDB[$medal][name]}\n操作:{$windid}\n理由：{$reason}",
	'metal_cancel'=>'收回勋章通知',
	'metal_cancel_content'=>"您的勋章被收回\n\n勋章名称：{$_MEDALDB[$medal][name]}\n操作:{$windid}\n理由：{$reason}",
	'metal_cancel_text'=>"您的勋章被收回\n\n勋章名称：$medalname\n操作:SYSTEM\n理由：过期",
	'vire_title'=>'交易币转帐通知',
	'vire_content'=>"用户 [b]{$windid}[/b] 使用交易币转帐功能，给您转帐 {$currency} 交易币，请注意查收。",
	'cyvire_title'=>"{$cn_name}交易币转帐通知",
	'cyvire_content'=>"{$cn_name}([url=$db_bbsurl/hack.php?H_name=colony&cyid=$cyid&job=view&id=$cyid]$cydb[cname][/url])管理员使用交易币管理功能，给你转帐 {$currency} 交易币，请注意查收。",
	'donate_title'=>"{$cn_name}捐献通知消息",
	'donate_content'=>"用户{$windid}通过捐献功能，给{$cn_name}({$cydb[cname]})捐献交易币：{$sendmoney}。",
	'join_title'=>"加入{$cn_name}通知消息",
	'join_content'=>"您已经成功加入{$cn_name}($cydb[cname]),[url=$db_bbsurl/hack.php?H_name=colony&cyid=$cyid&job=view&id=$cyid]马上开始体验[/url]",

	'top_title'		=> '您的文章被置顶.',
	'untop_title'	=> '您的文章被解除置顶.',
	'top_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]置顶[/b] 操作{$msg_add}",
	'untop_content'	=> "您的文章被 [b]{$msg[6]}[/b] 执行 [b]解除置顶[/b] 操作{$msg_add}",
	'digest_title'	=> '您的文章被设为精华帖',
	'digest_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]精华[/b] 操作\n对您的影响：{$msg[affect]}{$msg_add}",
	'undigest_title'	=> '您的文章被取消精华',
	'undigest_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]取消精华[/b] 操作\n对您的影响：{$msg[affect]}{$msg_add}",
	'lock_title'	=> '您的文章被锁定',
	'lock_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]锁定[/b] 操作{$msg_add}",
	'unlock_title'	=> '您的文章被解除锁定',
	'unlock_content'=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]解除锁定[/b] 操作{$msg_add}",
	'push_title'	=> '您的文章被提前',
	'push_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]提前[/b] 操作{$msg_add}",
	'unhighlight_title'	=> '您的文章标题被取消加亮显示',
	'unhighlight_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]标题取消加亮[/b] 操作{$msg_add}",
	'highlight_title'	=> '您的文章标题被加亮显示',
	'highlight_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]标题加亮[/b] 操作{$msg_add}",
	'del_title'	=> "您的文章被删除",
	'del_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]删除[/b] 操作\n对您的影响：{$msg[affect]}{$msg_add}",
	'move_title'	=> "您的文章被移动",
	'move_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]移动[/b] 操作\n\n[b]目的版块：[/b][url=$db_bbsurl/thread.php?fid={$msg[tofid]}]{$msg[toforum]}[/url]{$msg_add}",
	'copy_title'	=> "您的文章被复制到新版块",
	'copy_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]复制[/b] 操作\n\n[b]目的版块：[/b][url=$db_bbsurl/thread.php?fid={$msg[tofid]}]{$msg[toforum]}[/url]{$msg_add}",
	'ping_title'	=> "您的文章被评分",
	'ping_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]评分[/b] 操作\n\n对您的影响：{$msg[affect]}{$msg_add}",
	'delping_title' => "您的文章被取消评分",
	'delping_content'=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]取消评分[/b] 操作\n\n对您的影响：{$msg[affect]}{$msg_add}",
	'deltpc_title'	=> "您的文章被删除",
	'deltpc_content'	=> "您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]删除[/b] 操作\n\n对您的影响：{$msg[affect]}{$msg_add}",
	'delrp_title'	=> "您的回复被删除",
	'delrp_content'	=> "您发表的回复被 [b]{$msg[6]}[/b] 执行 [b]删除[/b] 操作\n\n对您的影响：{$msg[affect]}{$msg_add}",
	'reward_title'=>"您的回复被设为最佳答案!",
	'reward_content'=>"您的回复被设为最佳答案!\n\n对您的影响：{$msg[affect]}{$msg_add}",
	'endreward_title_1'=>"您的悬赏被取消!",
	'endreward_title_2'=>"您的悬赏被强制结案!",
	'endreward_content_1'=>"由于没有合适的答案，您的悬赏被管理员 [b]{$msg[6]}[/b] 执行 [b]取消[/b] 操作!\n\n系统返回您:{$msg[affect]}{$msg_add}",
	'endreward_content_2'=>"由于您长时间未对悬赏帖进行结案,且已经有合适的答案，所以被[b]{$msg[6]}[/b] 执行 [b]强制结案[/b] 操作\n\n系统不返回所有积分{$msg_add}",
	'rewardmsg_title'=>"悬赏帖(编号:$msg[tid])请求处理!",	'rewardmsg_content'=>"$msg[0]\t版主:\n\t\t您好!\n\t\t由于该次悬赏帖没有产生合适答案，现请求您结案,希望您仔细查证后，作出公平处理!{$msg_add}",
	'rewardmsg_notice_title'=>"悬赏帖到期通知!",	'rewardmsg_notice_content'=>"您的悬赏帖已经到期，系统提醒您尽快作出处理,否则版主有权强行结案!\n\n[b]文章：[/b][url=$db_bbsurl/read.php?tid=\$tid]\$msg[subject][/url]\n[b]发表日期：[/b]\$msg[postdate]\n[b]所在版块：[/b][url=$db_bbsurl/thread.php?fid=\$msg[fid]]\$msg[name][/url]\n\n论坛管理操作通知短消息，对本次管理操作有任何异议，请与我取得联系。",
	'send_credit'=>"管理团队工资发放!",
	'send_credit_content'=>"尊敬的 ltitle 们\n\t\t感谢你们对 $db_bbsname 的支持!现特发 addpoint $creditname 作为奖励.\n\n操作日期 $admindate",
	'shield_title_1'=>"您的文章被屏蔽",
	'shield_content_1'=>"您发表的文章被 [b]{$msg[6]}[/b] [b]屏蔽[/b]{$msg_add}",
	'shield_title_0'=>"您的文章被取消屏蔽",
	'shield_content_0'=>"由于操作失误,您发表的文章被 [b]{$msg[6]}[/b] [b]取消屏蔽[/b]{$msg_add},请见谅!",
	'report_title'=>"帖子报告处理",
	'report_content_1'=>"该帖很优秀,建议加为精华帖!{$msg_add}",
	'report_content_0'=>"该帖包含不良信息,请及时处理!{$msg_add}",
	'unite_title'=>'您的文章被合并',
	'unite_content'=>"您发表的文章被 [b]{$msg[6]}[/b] 执行 [b]合并[/b] 操作{$msg_add}",
);
?>