<?php
$msg_add = "<br><br><b>文章：</b><a href=\"read.php?tid=$msg[tid]\" target=\"_blank\">$msg[subject]</a><br><b>发表日期：</b>$msg[postdate]<br><b>所在版块：</b><a href=\"thread.php?fid=$msg[fid]\" target=\"_blank\">$msg[forum]</a><br><b>操作时间：</b>{$msg[admindate]}<br><b>操作理由：</b>$msg[reason]<br><br>论坛管理操作通知短消息，对本次管理操作有任何异议，请与我取得联系。";

$lang = array (
	'olpay_title'=>'交易币充值支付成功.',
	'olpay_content'=>"交易币充值支付成功，您需要登录支付宝使用“<font color=\"red\">确认收货</font>”功能完成本次交易。<br>确认收货后系统会自动对您的交易币帐户进行充值。",
	'olpay_content_2'=>"交易币充值成功，本次充值金额：{$number}RMB，总共获得交易币个数：{$currency}。<br>谢谢使用！",
	'virement_title'=>'银行汇款通知!!',
	'virement_content'=>"用户{$windid}通过银行给你转帐{$to_money}元钱，系统自动把以前的利息加到你的存款中，你的利息将从现在重新开始计算",

	'metal_add'=>'授予勋章通知',
	'metal_add_content'=>"您被授予勋章<br><br>勋章名称：{$_MEDALDB[$medal][name]}<br>操作:{$windid}<br>理由：{$reason}",
	'metal_cancel'=>'收回勋章通知',
	'metal_cancel_content'=>"您的勋章被收回<br><br>勋章名称：{$_MEDALDB[$medal][name]}<br>操作:{$windid}<br>理由：{$reason}",
	'vire_title'=>'交易币转帐通知',
	'vire_content'=>"用户 <b>{$windid}</b> 使用交易币转帐功能，给您转帐 {$currency} 交易币，请注意查收。",
	'cyvire_title'=>"{$cn_name}交易币转帐通知",
	'cyvire_content'=>"{$cn_name}(<a href=\"hack.php?H_name=colony&cyid=$cyid&job=view&id=$cyid\" target=\"_blank\">$cydb[cname]</a>)管理员使用交易币管理功能，给你转帐 {$currency} 交易币，请注意查收。",
	'donate_title'=>"{$cn_name}捐献通知消息",
	'donate_content'=>"用户{$windid}通过捐献功能，给{$cn_name}({$cydb[cname]})捐献交易币：{$sendmoney}。",
	'join_title'=>"加入{$cn_name}通知消息",
	'join_content'=>"您已经成功加入{$cn_name}($cydb[cname]),<a href=\"hack.php?H_name=colony&cyid=$cyid&job=view&id=$cyid\" target=\"_blank\">马上开始体验</a>",

	'top_title'		=> '您的文章被置顶.',
	'untop_title'	=> '您的文章被解除置顶.',
	'top_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>置顶</b> 操作{$msg_add}",
	'untop_content'	=> "您的文章被 <b>{$msg[6]}</b> 执行 <b>解除置顶</b> 操作{$msg_add}",
	'digest_title'	=> '您的文章被设为精华帖',
	'digest_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>精华</b> 操作<br>对您的影响操作：{$msg[affect]}{$msg_add}",
	'undigest_title'	=> '您的文章被取消精华',
	'undigest_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>取消精华</b> 操作<br>对您的影响操作：{$msg[affect]}{$msg_add}",
	'lock_title'	=> '您的文章被锁定',
	'lock_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>锁定</b> 操作{$msg_add}",
	'unlock_title'	=> '您的文章被解除锁定',
	'unlock_content'=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>解除锁定</b> 操作{$msg_add}",
	'push_title'	=> '您的文章被提前',
	'push_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>提前</b> 操作{$msg_add}",
	'highlight_title'	=> '您的文章标题被加亮显示',
	'highlight_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>标题加亮</b> 操作{$msg_add}",
	'del_title'	=> "您的文章被删除",
	'del_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>删除</b> 操作<br>对您的影响操作：{$msg[affect]}{$msg_add}",
	'move_title'	=> "您的文章被移动",
	'move_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>移动</b> 操作<br><br><b>目的版块：</b><a href=\"thread.php?fid={$msg[tofid]}\" target=\"_blank\">{$msg[toforum]}</a>{$msg_add}",
	'copy_title'	=> "您的文章被复制到新版块",
	'copy_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>复制</b> 操作<br><br><b>目的版块：</b><a href=\"thread.php?fid={$msg[tofid]}\" target=\"_blank\">{$msg[toforum]}</a>{$msg_add}",
	'ping_title'	=> "您的文章被评分",
	'ping_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>评分</b> 操作<br><br>对您的影响操作：{$msg[affect]}{$msg_add}",
	'deltpc_title'	=> "您的文章被删除",
	'deltpc_content'	=> "您发表的文章被 <b>{$msg[6]}</b> 执行 <b>删除</b> 操作<br><br>对您的影响操作：{$msg[affect]}{$msg_add}",
	'delrp_title'	=> "您的回复被删除",
	'delrp_content'	=> "您发表的回复被 <b>{$msg[6]}</b> 执行 <b>删除</b> 操作<br><br>对您的影响操作：{$msg[affect]}{$msg_add}",

);
?>